clc; clear; close all

figure(...
      'Color', 'w', ...
      'Units', 'Normalized', ...
      'Name', 'Figure 7 S1', ...
      'Position', [0.1 0.1 0.8 0.8]);
  
load(['D:\criticality_cognitive\project_synchrony_avalanche_fluid_Iq',...
    '\g_FC_complexity_analysis\static_FC_complexity.mat'], 'FCdiversity')
load(['D:\criticality_cognitive\project_synchrony_avalanche_fluid_Iq',...
    '\g_FC_complexity_analysis\static_FC_complexity.mat'], 'FCentropy')
load(['D:\criticality_cognitive\project_synchrony_avalanche_fluid_Iq',...
    '\g_FC_complexity_analysis\flexibility.mat'], 'CNE_subject')
load(['D:\criticality_cognitive\project_synchrony_avalanche_fluid_Iq',...
    '\b_MS_SE_STATIC\MS_SE_Z1024_RS.mat'], 'subject')
load('HCP_iq0804.mat', 'Subject')
load('HCP_iq0804.mat', 'ListSort_Unadj')
load('HCP_iq0804.mat', 'PMAT24_A_CR')
load('HCP_iq0804.mat', 'PicVocab_Unadj')

% select the subject 
for i = 1 : 295
    for j = 1 : 1206
        if subject(i) == Subject(j)
            PMAT(i, 1) = PMAT24_A_CR(j);
            Listsorting(i, 1) = ListSort_Unadj(j);
            PictureVocab(i, 1) = PicVocab_Unadj(j);
        end
    end
end

%% figure 7 S a
index_PMAT = find(PMAT > -1000);
[fit_FCE_PMAT] = createFit_poly1(FCentropy(index_PMAT,1), PMAT(index_PMAT,1));
p1 = fit_FCE_PMAT.p1; 
p2 = fit_FCE_PMAT.p2; 
F7_S1_a.FCE = FCentropy(index_PMAT,1);
F7_S1_a.PMAT = PMAT(index_PMAT,1);
F7_S1_a.fitX = min(FCentropy(index_PMAT,1))-0.1:0.1:max(FCentropy(index_PMAT,1))+0.1;
F7_S1_a.fitY = p1 .* F7_S1_a.fitX + p2;
F7_S1_a.fitResult = fit_FCE_PMAT;

[R_SE_PMAT,P_SE_PMAT] = corr(F7_S1_a.FCE, F7_S1_a.PMAT);

AX1 = subplot(2,3,1);
plot(F7_S1_a.FCE, F7_S1_a.PMAT, 'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', 'Linewidth', 2, ...
    'Marker', 'o', 'MarkerSize', 5);
hold on
f1 = plot(F7_S1_a.fitX, F7_S1_a.fitY, 'Color', [1,0,0], ...
    'LineStyle', '--', 'Linewidth', 2.5, ...
    'Marker', 'none', 'MarkerSize', 2.5);
set(gca, 'FontName', 'Arial', 'FontSize', 12)
lgd = legend(f1, '$fit$', 'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.95, ['$R=', num2str(round(R_SE_PMAT,2)), '$'], ...
    'units', 'normalized', 'Interpreter', 'latex', ...
    'FontName', 'Arial', 'FontSize', 18);
text(0.80, 0.85, ['$p=', num2str(round(P_SE_PMAT,2)), '$'], ...
    'units', 'normalized', 'Interpreter', 'latex', ...
    'FontName', 'Arial', 'FontSize', 18);
ylim([-3 35])
xlabel('FC entropy H(FC)', 'FontName', 'Arial', 'FontSize', 15);
ylabel('PMAT', 'FontName', 'Arial', 'FontSize', 15);
title('a', 'FontName', 'Arial', ...
    'FontSize', 24, 'FontWeight', 'bold', ...
    'units','normalized', 'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off
%% figure 7 S d
index_Listsorting = find(Listsorting > -1000);
[fit_FCE_ListSort] = createFit_poly1(FCentropy(index_Listsorting,1), Listsorting(index_Listsorting,1));
p1 = fit_FCE_ListSort.p1; 
p2 = fit_FCE_ListSort.p2; 
F7_S1_d.FCE = FCentropy(index_Listsorting,1);
F7_S1_d.ListSortingWorkMemory = Listsorting(index_Listsorting,1);
F7_S1_d.fitX = min(FCentropy(index_Listsorting,1))-0.1:0.1:max(FCentropy(index_Listsorting,1))+0.1;
F7_S1_d.fitY = p1 .* F7_S1_d.fitX + p2;
F7_S1_d.fitResult = fit_FCE_ListSort;

[R_SE_ListSort,P_SE_ListSort] = corr(F7_S1_d.FCE, F7_S1_d.ListSortingWorkMemory);
AX1 = subplot(2,3,4);
plot(F7_S1_d.FCE, F7_S1_d.ListSortingWorkMemory, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', ...
    'Linewidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 5);
hold on
f1 = plot(F7_S1_d.fitX, F7_S1_d.fitY, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'Linewidth', 2.5, ...
    'Marker', 'none', ...
    'MarkerSize', 2.5);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
lgd = legend(f1, '$fit$', ...
    'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.95, ['$R=', num2str(round(R_SE_ListSort,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize',18);
text(0.80, 0.85, ['$p=', num2str(round(P_SE_ListSort,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
ylim([60 165])
xlabel('FC entropy H(FC)', ...
    'FontName', 'Arial', ...
    'FontSize',15);
ylabel('List sorting', ...
    'FontName', 'Arial', ...
    'FontSize', 15)
title('d', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units', 'normalized',...
    'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off
%% figure 7 S b
index_PMAT = find(PMAT > -1000);
[fit_FCD_PMAT] = createFit_poly1(FCdiversity(index_PMAT,1), PMAT(index_PMAT,1));
p1 = fit_FCD_PMAT.p1; 
p2 = fit_FCD_PMAT.p2; 
Figure_7_S_b.FCD = FCdiversity(index_PMAT,1);
Figure_7_S_b.PMAT = PMAT(index_PMAT,1);
Figure_7_S_b.fitX = min(FCdiversity(index_PMAT,1))-0.1:0.1:max(FCdiversity(index_PMAT,1))+0.1;
Figure_7_S_b.fitY = p1 .* Figure_7_S_b.fitX + p2;
Figure_7_S_b.fitResult = fit_FCD_PMAT;

[R_SE_PMAT,P_SE_PMAT] = corr(Figure_7_S_b.FCD, Figure_7_S_b.PMAT);

AX1 = subplot(2,3,2);
plot(Figure_7_S_b.FCD, Figure_7_S_b.PMAT, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', ...
    'Linewidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 5);
hold on
f1 = plot(Figure_7_S_b.fitX, Figure_7_S_b.fitY, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'Linewidth', 2.5, ...
    'Marker', 'none', ...
    'MarkerSize', 2.5);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
lgd = legend(f1, '$fit$', ...
    'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.95, ['$R=', num2str(round(R_SE_PMAT,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
text(0.80, 0.85, ['$p=', num2str(round(P_SE_PMAT,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
ylim([-3 35])
xlabel('FC diversity D(FC)', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
ylabel('PMAT', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
title('b', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units','normalized',...
    'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off
%% figure 7 S e
index_Listsorting = find(Listsorting > -1000);
[fit_FCD_ListSort] = createFit_poly1(FCdiversity(index_Listsorting,1), Listsorting(index_Listsorting,1));
p1 = fit_FCD_ListSort.p1; 
p2 = fit_FCD_ListSort.p2; 
Figure_7_S_e.FCD = FCdiversity(index_Listsorting,1);
Figure_7_S_e.ListSortingWorkMemory = Listsorting(index_Listsorting,1);
Figure_7_S_e.fitX = min(FCdiversity(index_Listsorting,1))-0.1:0.1:max(FCdiversity(index_Listsorting,1))+0.1;
Figure_7_S_e.fitY = p1 .* Figure_7_S_e.fitX + p2;
Figure_7_S_e.fitResult = fit_FCD_ListSort;

[R_SE_ListSort,P_SE_ListSort] = corr(Figure_7_S_e.FCD, Figure_7_S_e.ListSortingWorkMemory);
AX1 = subplot(2,3,5);
plot(Figure_7_S_e.FCD, Figure_7_S_e.ListSortingWorkMemory, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', ...
    'Linewidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 5);
hold on
f1 = plot(Figure_7_S_e.fitX, Figure_7_S_e.fitY, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'Linewidth', 2.5, ...
    'Marker', 'none', ...
    'MarkerSize', 2.5);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
lgd = legend(f1, '$fit$', ...
    'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.95, ['$R=', num2str(round(R_SE_ListSort,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize',18);
text(0.80, 0.85, ['$p=', num2str(round(P_SE_ListSort,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
ylim([60 165])
xlabel('FC diversity D(FC)', ...
    'FontName', 'Arial', ...
    'FontSize',15);
ylabel('List sorting', ...
    'FontName', 'Arial', ...
    'FontSize', 15)
title('e', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units', 'normalized',...
    'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off
%% figure 7 S c
index_PMAT = find(PMAT > -1000);
[fit_FCCNE_PMAT] = createFit_poly1(CNE_subject(index_PMAT,1), PMAT(index_PMAT,1));
p1 = fit_FCCNE_PMAT.p1; 
p2 = fit_FCCNE_PMAT.p2; 
Figure_7_S_c.FCCNE = CNE_subject(index_PMAT,1);
Figure_7_S_c.PMAT = PMAT(index_PMAT,1);
Figure_7_S_c.fitX = min(CNE_subject(index_PMAT,1))-0.1:0.1:max(CNE_subject(index_PMAT,1))+0.1;
Figure_7_S_c.fitY = p1 .* Figure_7_S_c.fitX + p2;
Figure_7_S_c.fitResult = fit_FCCNE_PMAT;

[R_SE_PMAT,P_SE_PMAT] = corr(Figure_7_S_c.FCCNE, Figure_7_S_c.PMAT);

AX1 = subplot(2,3,3);
plot(Figure_7_S_c.FCCNE, Figure_7_S_c.PMAT, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', ...
    'Linewidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 5);
hold on
f1 = plot(Figure_7_S_c.fitX, Figure_7_S_c.fitY, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'Linewidth', 2.5, ...
    'Marker', 'none', ...
    'MarkerSize', 2.5);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
lgd = legend(f1, '$fit$', ...
    'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.95, ['$R=', num2str(round(R_SE_PMAT,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
text(0.80, 0.85, ['$p=', num2str(round(P_SE_PMAT,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
ylim([-3 35])
xlabel('flexibility CNE', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
ylabel('PMAT', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
title('c', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units','normalized',...
    'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off

%% figure 7 S f
index_Listsorting = find(Listsorting > -1000);
[fit_CNE_ListSort] = createFit_poly1(CNE_subject(index_Listsorting,1), Listsorting(index_Listsorting,1));
p1 = fit_CNE_ListSort.p1; 
p2 = fit_CNE_ListSort.p2; 
Figure_7_S_f.CNE = CNE_subject(index_Listsorting,1);
Figure_7_S_f.ListSortingWorkMemory = Listsorting(index_Listsorting,1);
Figure_7_S_f.fitX = min(CNE_subject(index_Listsorting,1))-0.1:0.1:max(CNE_subject(index_Listsorting,1))+0.1;
Figure_7_S_f.fitY = p1 .* Figure_7_S_f.fitX + p2;
Figure_7_S_f.fitResult = fit_CNE_ListSort;

[R_SE_ListSort,P_SE_ListSort] = corr(Figure_7_S_f.CNE, Figure_7_S_f.ListSortingWorkMemory);
AX1 = subplot(2,3,6);
plot(Figure_7_S_f.CNE, Figure_7_S_f.ListSortingWorkMemory, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', ...
    'Linewidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 5);
hold on
f1 = plot(Figure_7_S_f.fitX, Figure_7_S_f.fitY, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'Linewidth', 2.5, ...
    'Marker', 'none', ...
    'MarkerSize', 2.5);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
lgd = legend(f1, '$fit$', ...
    'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.95, ['$R=', num2str(round(R_SE_ListSort,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize',18);
text(0.80, 0.85, ['$p=', num2str(round(P_SE_ListSort,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
ylim([60 165])
xlabel('flexibility CNE', ...
    'FontName', 'Arial', ...
    'FontSize',15);
ylabel('List sorting', ...
    'FontName', 'Arial', ...
    'FontSize', 15)
title('f', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units', 'normalized',...
    'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off

