% plot the robust relationship between the MS and SE
clc;
clear;
close all;

figure('Color', 'w', 'Units', 'Normalized', ...
    'Name', ['The robustness of inverted-U curve',...
    ' between MS and SE against choice of parcellation'], ...
    'Position', [0.1 0.1 0.8 0.8]);

load(fullfile('step_2_MS_SE_relationship','results.mat'));
LMS = LMHgroup.LMS;
MMS = LMHgroup.MMS;
HMS = LMHgroup.HMS;
%% HY-96 
for sub = 1:295
    MS_HY96(sub) = results_HY(sub).mean_kop;
    SE_HY96(sub) = results_HY(sub).entropy_kop;
end 
AX1 = subplot(2,3,1);
plot(MS_HY96, SE_HY96, ...
    'Color',[0.5,0.5,0.5],...
    'Marker','o', ...
    'MarkerSize',6, ...
    'LineWidth',2, ...
    'LineStyle','none'); % plot the MS and SE
hold on
f2 = plot(MS_HY96(LMS(:,3)), SE_HY96(LMS(:,3)),...
    'Color',[0,0,1],...
    'Marker','o', ...
    'MarkerSize',6, ...
    'LineWidth',2, ...
    'LineStyle','none');
f3 = plot(MS_HY96(MMS(:,3)),SE_HY96(MMS(:,3)),...
    'Color',[0,1,0],...
    'Marker','o', ...
    'MarkerSize',6, ...
    'LineWidth',2, ...
    'LineStyle','none');
% marker the HMS
f4 = plot(MS_HY96(HMS(:,3)), SE_HY96(HMS(:,3)),...
    'Color',[1,0,0],...
    'Marker','o', 'MarkerSize',6,...
    'LineWidth',2, 'LineStyle','none');
[~, fitx, fity] = f_fit_poly2(MS_HY96, SE_HY96);
f1 = plot(fitx, fity, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
xlim([min(MS_HY96)-0.05,max(MS_HY96)+0.05]);
set(gca, 'FontName', 'Arial', 'FontSize', 12);
legend([f1,f2,f3,f4],{'$fit$','LMS','MMS','HMS'},...
    'Interpreter','latex',...
    'Location','northeast',...
    'FontName','Arial', 'FontSize',15,...
    'EdgeColor',[1,1,1])
legend('boxoff')
xlabel('Atlas_9_6 MS <r>',...
    'FontName','Arial',...
    'FontSize',15);
ylabel('Atlas_9_6 SE H(r)',...
    'FontName','Arial',...
    'FontSize',15);
box(AX1,'off'); 
AX1.LineWidth=2; 
grid off; 
hold off;
title('(a)', ...
    'FontName', 'Arial',...
    'FontSize',24, ...
    'FontWeight', 'bold',...
    'units','normalized',...
    'position',[-1/18,1+1/10],...
    'HorizontalAlignment','right',...
    'VerticalAlignment','bottom');

%% BN-246
for sub = 1:295
    MS_BN246(sub) = results_BN246(sub).mean_kop;
    SE_BN246(sub) = results_BN246(sub).entropy_kop;
end 
AX1=subplot(2,3,2);
plot(MS_BN246, SE_BN246,...
    'Color',[0.5,0.5,0.5],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
hold on
f2 = plot(MS_BN246(LMS(:,3)), SE_BN246(LMS(:,3)),...
    'Color',[0,0,1],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
f3 = plot(MS_BN246(MMS(:,3)), SE_BN246(MMS(:,3)),...
    'Color',[0,1,0],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
f4 = plot(MS_BN246(HMS(:,3)), SE_BN246(HMS(:,3)),...
    'Color',[1,0,0],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
[~, fitx, fity] = f_fit_poly2(MS_BN246, SE_BN246);
f1=plot(fitx, fity, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
xlim([min(MS_BN246)-0.05, max(MS_BN246)+0.05]);
set(gca,...
    'FontName','Arial',...
    'FontSize',12);
legend([f1,f2,f3,f4],{'$fit$','LMS','MMS','HMS'},...
    'Interpreter','latex',...
    'Location','southeast',...
    'FontName','Arial',...
    'FontSize',15,...
    'EdgeColor',[1,1,1])
legend('boxoff')
xlabel('Atlas_2_4_6 MS <r>',...
    'FontName','Arial',...
    'FontSize',15);
ylabel('Atlas_2_4_6 SE H(r)',...
    'FontName','Arial',...
    'FontSize',15);
box(AX1,'off'); 
AX1.LineWidth = 2; 
grid off; 
hold off;
title('(b)',...
    'FontName','Arial',...
    'FontSize',24, ...
    'FontWeight', 'bold',...
    'units','normalized',...
    'position',[-1/18,1+1/10],...
    'HorizontalAlignment','right',...
    'VerticalAlignment','bottom');
%% Z-1024
for sub = 1:295
    MS_Z1024(sub) = results_Z(sub).mean_kop;
    SE_Z1024(sub) = results_Z(sub).entropy_kop;
end 
AX1 = subplot(2,3,3);
plot(MS_Z1024,SE_Z1024,...
    'Color',[0.5,0.5,0.5],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
hold on
f2 = plot(MS_Z1024(LMS(:,3)),...
    SE_Z1024(LMS(:,3)),...
    'Color',[0,0,1],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
f3 = plot(MS_Z1024(MMS(:,3)),....
    SE_Z1024(MMS(:,3)),...
    'Color',[0,1,0],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
f4 = plot(MS_Z1024(HMS(:,3)),...
    SE_Z1024(HMS(:,3)),...
    'Color',[1,0,0],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
[~, fitX, fitY] = f_fit_poly2(MS_Z1024, SE_Z1024);
f1 = plot(fitX, fitY,...
    'Color',[1,0,0],...
    'LineStyle','--',...
    'LineWidth',2.5);
xlim([min(MS_Z1024)-0.05, max(MS_Z1024)+0.05]);
set(gca,...
    'FontName','Arial',...
    'FontSize',12);
legend([f1,f2,f3,f4], {'$fit$','LMS','MMS','HMS'},...
    'Interpreter', 'latex',...
    'Location', 'southeast',...
    'FontName', 'Arial',...
    'FontSize', 15,...
    'EdgeColor',[1,1,1])
legend('boxoff')
xlabel('Atlas_1_0_2_4 MS <r>',...
    'FontName','Arial',...
    'FontSize',15);
ylabel('Atlas_1_0_2_4 SE H(r)',...
    'FontName','Arial',...
    'FontSize',15);
box(AX1,'off'); 
AX1.LineWidth=2; 
grid off; 
hold off;
title('(c)',...
    'FontName','Arial',...
    'FontSize',24, ...
    'FontWeight', 'bold',...
    'units','normalized',...
    'position',[-1/18,1+1/10],...
    'HorizontalAlignment','right',...
    'VerticalAlignment','bottom');
%%
AX1 = subplot(2,3,4);
plot(SE_HY96, SE_BN246, ...
    'Color',[0.5,0.5,0.5], ...
    'Marker','o', ...
    'MarkerSize',6, ...
    'LineWidth',2, ...
    'LineStyle','none');
hold on
[~, fitX, fitY] = f_fit_poly1(SE_HY96, SE_BN246);
[R_SE96_SE246, P_SE96_SE246] = corr(SE_HY96', SE_BN246');

f1 = plot(fitX, fitY, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'Linewidth', 2.5, ...
    'Marker', 'none', ...
    'MarkerSize', 2.5);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
lgd = legend(f1, '$fit$', ...
    'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.35, ['$R=', num2str(round(R_SE96_SE246,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
text(0.80, 0.2, ['$p=', num2str(round(P_SE96_SE246,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
xlabel('Atlas_9_6 SE', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
ylabel('Atlas_2_4_6 SE', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
title('(d)', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units','normalized',...
    'position', [-1/18,1+1/10], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off
%%
AX1 = subplot(2,3,5);
plot(SE_HY96, SE_Z1024,...
    'Color',[0.5,0.5,0.5],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
hold on
[~, fitX, fitY] = f_fit_poly1(SE_HY96, SE_Z1024);
[R_SE96_SE1024,P_SE96_SE1024] = corr(SE_HY96', SE_Z1024');

f1 = plot(fitX, fitY, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'Linewidth', 2.5, ...
    'Marker', 'none', ...
    'MarkerSize', 2.5);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
lgd = legend(f1, '$fit$', ...
    'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.35, ['$R=', num2str(round(R_SE96_SE1024,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
text(0.80, 0.2, ['$p=', num2str(round(P_SE96_SE1024,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
xlabel('Atlas_9_6 SE', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
ylabel('Atlas_1_0_2_4 SE', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
title('(e)', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units','normalized',...
    'position', [-1/18,1+1/10], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off
%%
AX1 = subplot(2,3,6);
plot(SE_BN246, SE_Z1024,...
    'Color',[0.5,0.5,0.5],...
    'Marker','o',...
    'MarkerSize',6,...
    'LineWidth',2,...
    'LineStyle','none');
hold on
[~, fitX, fitY] = f_fit_poly1(SE_BN246, SE_Z1024);
[R_SE246_SE1024, P_SE246_SE1024] = corr(SE_BN246', SE_Z1024');

f1 = plot(fitX, fitY, ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'Linewidth', 2.5, ...
    'Marker', 'none', ...
    'MarkerSize', 2.5);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
lgd = legend(f1, '$fit$', ...
    'Interpreter', 'latex');
legend('boxoff');
lgd.NumColumns = 1;
lgd.FontName = 'Arial';
lgd.FontSize = 15;
lgd.Location = 'northwest';
text(0.80, 0.35, ['$R=', num2str(round(R_SE246_SE1024,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
text(0.80, 0.2, ['$p=', num2str(round(P_SE246_SE1024,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontName', 'Arial', ...
    'FontSize', 18);
xlabel('Atlas_2_4_6 SE', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
ylabel('Atlas_1_0_2_4 SE', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
title('(f)', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units','normalized',...
    'position', [-1/18,1+1/10], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
grid off; 
box(AX1,'off'); 
AX1.LineWidth = 2; 
hold off
