clc;clear;close all
addpath('CritAnalysisSoftwarePackage2016-04-25');
figure(...
      'Color', 'w', ...
      'Units', 'Normalized', ...
      'Name', 'Figure 1 Power-law distribution fot the aggregate level reflecting the brain near criticality in the resting state', ...
      'Position', [0.1 0.1 0.8 0.8]);

Label_size = 18;
Title_size = 24;
Text_size = 20;
  
load('avalanches_HMS_1.4.mat', 'ava_size_HMS')
load('avalanches_HMS_1.4.mat', 'ava_duration_HMS')
load('avalanches_HMS_1.4.mat', 'average_size_HMS')
load('avalanches_HMS_1.4.mat', 'lifetime_HMS')
S = ava_size_HMS;
T = ava_duration_HMS;
Smax2fit = 30; 
Smin2fit = 3;
Tmax2fit = 9; 
Tmin2fit=2;

%% 
ax1 = subplot(3, 3, 1);
S_p = hist(S, min(S):max(S));
loglog(min(S):max(S), S_p./S_p(1), ...
    'Color', [0.50,0.50,0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on;
[alpha_mle_HMS, Smin2fit, Smax2fit] = plmle(S, 'xmin', Smin2fit, 'xmax', Smax2fit);
[p_alpha_mle_HMS] = pvcalc(S, alpha_mle_HMS, 'xmin',Smin2fit,'xmax',Smax2fit);
loglog(Smin2fit:Smax2fit, (Smin2fit:Smax2fit).^(-alpha_mle_HMS), ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
text(0.6, 0.9, ['$\alpha=', num2str(round(alpha_mle_HMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter','latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor','none');
text(0.6, 0.7, ['$p=', num2str(round(p_alpha_mle_HMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanche size S', ...
    'FontName', 'Arial');
ylabel('P(S)', ...
    'FontName', 'Arial');
xlim([1,1000]);
ylim([0.0001,1]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', Label_size, ...
    'XTick', [1, 10, 100, 1000], ...
    'YTick', [0.00001, 0.0001, 0.001, 0.01, 0.1,1]);
grid off; 
ax1.LineWidth=2; 
box(ax1, 'off'); 
hold off
title('a', ...
    'FontName', 'Arial', ...
    'FontSize', Title_size, ...
    'FontWeight', 'bold', ...
    'units', 'normalized', ...
    'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');

%%
ax1 = subplot(3,3,2);
T_p = hist(T, min(T):max(T));
loglog(min(T):max(T), T_p./T_p(1), ...
    'Color', [0.50,0.50,0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on;
[tau_mle_HMS, Tmin2fit, Tmax2fit] = plmle(T,'xmin',Tmin2fit,'xmax',Tmax2fit);
[p_tau_mle_HMS] = pvcalc(T, tau_mle_HMS, 'xmin',Tmin2fit,'xmax',Tmax2fit);
loglog(Tmin2fit:Tmax2fit, (Tmin2fit:Tmax2fit).^(-tau_mle_HMS), ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
text(0.6, 0.9, ['$\tau=', num2str(round(tau_mle_HMS, 2)), '$'],...
    'units', 'normalized', ...
    'Interpreter','latex',...
    'Color', [0.00, 0.00, 0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
text(0.6, 0.7, ['$p= ', num2str(round(p_tau_mle_HMS, 2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter','latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanche duration T', ...
    'FontName', 'Arial');
ylabel('P(T)', ...
    'FontName', 'Arial');
xlim([1, 100])
ylim([0.0001, 1]);
set(gca, ...
    'FontName', 'Arial',...
    'FontSize', Label_size, ...
    'XTick', [1, 10, 100, 1000], ...
    'YTick', [0.00001, 0.0001, 0.001, 0.01, 0.1, 1]);
title('HMS', ...
    'FontName', 'Arial', ...
    'FontSize', Title_size);
grid off; 
ax1.LineWidth = 2; 
box(ax1, 'off');
hold off
%%
ax1 = subplot(3, 3, 3);
gamma_mle_HMS = (tau_mle_HMS-1)/(alpha_mle_HMS-1);
loglog(lifetime_HMS, average_size_HMS, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on
[gamma_nlsfit_HMS] = createFit_pl_nonlinearLS(lifetime_HMS(Tmin2fit:Tmax2fit), average_size_HMS(Tmin2fit:Tmax2fit));
loglog(Tmin2fit:Tmax2fit, (gamma_nlsfit_HMS.a).*(Tmin2fit:Tmax2fit).^(gamma_nlsfit_HMS.b), ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
text(0.15, 0.9, ['$\frac{\tau-1}{\alpha-1}=', num2str(round(gamma_mle_HMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
text(0.15, 0.7, ...
    ['$\gamma= ', num2str(round(gamma_nlsfit_HMS.b,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter','latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanche duration T', ...
    'FontName', 'Arial');
ylabel('average size <S>', ...
    'FontName', 'Arial');
xlim([1,100]);
ylim([1,1000]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', Label_size, ...
    'XTick', [1,10,100,1000], ...
    'YTick', [1,10,100,1000]);
box(ax1,'off'); 
ax1.LineWidth = 2; 
grid off; 
hold off

% MMS
load('avalanches_MMS_1.4.mat', 'ava_duration_MMS')
load('avalanches_MMS_1.4.mat', 'ava_size_MMS')
load('avalanches_MMS_1.4.mat', 'average_size_MMS')
load('avalanches_MMS_1.4.mat', 'lifetime_MMS')
clear S T
S = ava_size_MMS;
T = ava_duration_MMS;
Smax2fit = 30; 
Smin2fit=3;
Tmax2fit = 9; 
Tmin2fit=2;
%% 
ax1 = subplot(3,3,4);
S_p = hist(S, min(S):max(S));
loglog(min(S):max(S), S_p./S_p(1), ...
    'Color', [0.50,0.50,0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on;
[alpha_mle_MMS, Smin2fit, Smax2fit] = plmle(S, 'xmin', Smin2fit, 'xmax', Smax2fit);
[p_alpha_mle_MMS] = pvcalc(S, alpha_mle_MMS, 'xmin', Smin2fit, 'xmax',Smax2fit);
loglog(Smin2fit:Smax2fit, (Smin2fit:Smax2fit).^(-alpha_mle_MMS), ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth',2.5);
text(0.6, 0.9, ['$\alpha= ', num2str(round(alpha_mle_MMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial',...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
text(0.6, 0.7, ['$p= ', num2str(round(p_alpha_mle_MMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanche size S', ...
    'FontName', 'Arial');
ylabel('P(S)', ...
    'FontName', 'Arial');
xlim([1, 1000]); 
ylim([0.0001, 1])
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', Label_size, ...
    'XTick', [1, 10, 100, 1000], ...
    'YTick', [0.00001, 0.0001, 0.001, 0.01, 0.1, 1]);
grid off; 
ax1.LineWidth = 2; 
box(ax1, 'off'); 
hold off
title('b', ...
    'FontName', 'Arial', ...
    'FontSize', Title_size, ...
    'FontWeight', 'bold', ...
    'units', 'normalized', ...
    'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
%%
ax1 = subplot(3,3,5);
T_p = hist(T, min(T):max(T));
loglog(min(T):max(T), T_p./T_p(1), ...
    'Color', [0.50,0.50,0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on;
[tau_mle_MMS, Tmin2fit, Tmax2fit] = plmle(T, 'xmin', Tmin2fit, 'xmax', Tmax2fit);
[p_tau_mle_MMS] = pvcalc(T, tau_mle_MMS, 'xmin',Tmin2fit,'xmax',Tmax2fit);
loglog(Tmin2fit:Tmax2fit, (Tmin2fit:Tmax2fit).^(-tau_mle_MMS), ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);

text(0.6, 0.9, ['$\tau= ',num2str(round(tau_mle_MMS,2)),'$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
text(0.6, 0.7, ['$p= ',num2str(round(p_tau_mle_MMS,2)),'$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanche duration T', ...
    'FontName', 'Arial', ...
    'FontSize', Label_size);
ylabel('P(T)', ...
    'FontName', 'Arial', ...
    'FontSize', Label_size);
xlim([1, 100]);
ylim([0.0001, 1]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', Label_size, ...
    'XTick', [1, 10, 100, 1000], ...
    'YTick', [0.00001, 0.0001, 0.001, 0.01, 0.1, 1]);
grid off; 
ax1.LineWidth=2; 
box(ax1,'off'); 
hold off
title('MMS', ...
    'FontName', 'Arial', ...
    'FontSize', Title_size);

ax1 = subplot(3,3,6);
gamma_mle_MMS = (tau_mle_MMS-1)/(alpha_mle_MMS-1);
loglog(lifetime_MMS, average_size_MMS, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on
[gamma_nlsfit_MMS] = createFit_pl_nonlinearLS(lifetime_MMS(Tmin2fit:Tmax2fit), average_size_MMS(Tmin2fit:Tmax2fit));
loglog(Tmin2fit:Tmax2fit, (gamma_nlsfit_MMS.a).*(Tmin2fit:Tmax2fit).^(gamma_nlsfit_MMS.b), ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'LineWidth',2.5);

text(0.15, 0.9, ['$\frac{\tau-1}{\alpha-1}=', num2str(round(gamma_mle_MMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
text(0.15, 0.7, ['$\gamma=', num2str(round(gamma_nlsfit_MMS.b,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanche duration T', ...
    'FontName', 'Arial');
ylabel('average size <S>', ...
    'FontName', 'Arial');
xlim([1, 100]);
ylim([1, 1000]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', Label_size, ...
    'XTick', [1,10,100,1000], ...
    'YTick', [1,10,100,1000]);
box(ax1,'off'); 
ax1.LineWidth = 2; 
grid off; 
hold off
%%
load('avalanches_LMS_1.4.mat', 'ava_duration_LMS')
load('avalanches_LMS_1.4.mat', 'ava_size_LMS')
load('avalanches_LMS_1.4.mat', 'average_size_LMS')
load('avalanches_LMS_1.4.mat', 'lifetime_LMS')
clear S T
S = ava_size_LMS;
T = ava_duration_LMS;
Smax2fit = 30; Smin2fit=3;
Tmax2fit = 9; Tmin2fit=2;
%% 
ax1 = subplot(3,3,7);
S_p = hist(S,min(S):max(S));
loglog(min(S):max(S), S_p./S_p(1), ...
    'Color', [0.50,0.50,0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on;
[alpha_mle_LMS, Smin2fit, Smax2fit] = plmle(S,'xmin',Smin2fit,'xmax',Smax2fit);
[p_alpha_mle_LMS, ks_alpha_mle] = pvcalc(S, alpha_mle_LMS, 'xmin',Smin2fit,'xmax',Smax2fit);
loglog(Smin2fit:Smax2fit, (Smin2fit:Smax2fit).^(-alpha_mle_LMS), ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth',2.5);

text(0.6, 0.9, ['$\alpha= ',num2str(round(alpha_mle_LMS,2)),'$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor','none');
text(0.6, 0.7, ['$p= ', num2str(round(p_alpha_mle_LMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanche size S', ...
    'FontName', 'Arial');
ylabel('P(S)', ...
    'FontName', 'Arial');
xlim([1, 1000]); 
ylim([0.0001, 1]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', Label_size, ...
    'XTick', [1, 10, 100, 1000], ...
    'YTick', [0.00001, 0.0001, 0.001, 0.01, 0.1, 1]);
grid off; 
ax1.LineWidth = 2; 
box(ax1,'off'); 
hold off
title('c', ...
    'FontName', 'Arial', ...
    'FontSize', Title_size, ...
    'FontWeight', 'bold', ....
    'units', 'normalized', ...
    'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
%%
ax1 = subplot(3,3,8);
T_p = hist(T,min(T):max(T));
loglog(min(T):max(T), T_p./T_p(1), ...
    'Color', [0.50,0.50,0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on;
[tau_mle_LMS, Tmin2fit, Tmax2fit] = plmle(T, 'xmin', Tmin2fit, 'xmax', Tmax2fit);
[p_tau_mle_LMS, ks_tau_mle] = pvcalc(T, tau_mle_LMS, 'xmin',Tmin2fit,'xmax',Tmax2fit);
loglog(Tmin2fit:Tmax2fit, (Tmin2fit:Tmax2fit).^(-tau_mle_LMS), ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
text(0.6, 0.9, ['$\tau=', num2str(round(tau_mle_LMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter','latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none'); 
text(0.6, 0.7, ['$p= ',num2str(round(p_tau_mle_LMS,2)),'$'], ...
    'units', 'normalized', ...
    'Interpreter','latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanches duration T', ...
    'FontName', 'Arial');
ylabel('P(T)', ...
    'FontName', 'Arial');
xlim([1,100]);
ylim([0.0001,1])
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', Label_size, ...
    'XTick', [1, 10, 100, 1000], ...
    'YTick', [0.00001, 0.0001, 0.001, 0.01, 0.1, 1]);
title('LMS', ...
    'FontName', 'Arial', ....
    'FontSize', Title_size);
grid off; 
ax1.LineWidth = 2; 
box(ax1,'off'); 
hold off
%%
ax1 = subplot(3,3,9);
gamma_mle_LMS = (tau_mle_LMS-1)/(alpha_mle_LMS-1);
loglog(lifetime_LMS, average_size_LMS, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on
[gamma_nlsfit_LMS] = createFit_pl_nonlinearLS(lifetime_LMS(Tmin2fit:Tmax2fit), average_size_LMS(Tmin2fit:Tmax2fit));
loglog(Tmin2fit:Tmax2fit, (gamma_nlsfit_LMS.a).*(Tmin2fit:Tmax2fit).^(gamma_nlsfit_LMS.b), ...
    'Color', [1,0,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
text(0.15, 0.9, ['$\frac{\tau-1}{\alpha-1}=', num2str(round(gamma_mle_LMS,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
text(0.15, 0.7, ['$\gamma=', num2str(round(gamma_nlsfit_LMS.b,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter','latex',...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', Text_size, ...
    'EdgeColor', 'none');
xlabel('avalanche duration T', ...
    'FontName', 'Arial');
ylabel('average size <S>', ...
    'FontName', 'Arial');
xlim([1, 100]);
ylim([1, 1000])
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', Label_size, ...
    'XTick', [1, 10, 100, 1000], ...
    'YTick', [1, 10, 100, 1000]);
box(ax1,'off'); 
ax1.LineWidth=2; 
grid off; 
hold off

criteria.alpha_HMS = alpha_mle_HMS;
criteria.alpha_LMS = alpha_mle_LMS;
criteria.alpha_MMS = alpha_mle_MMS;
criteria.tau_HMS = tau_mle_HMS;
criteria.tau_MMS = tau_mle_MMS;
criteria.tau_LMS = tau_mle_LMS;
criteria.gammafit_HMS = gamma_nlsfit_HMS;
criteria.gammafit_MMS = gamma_nlsfit_MMS;
criteria.gammafit_LMS = gamma_nlsfit_LMS;
criteria.gamma_HMS = gamma_mle_HMS;
criteria.gamma_MMS = gamma_mle_MMS;
criteria.gamma_LMS = gamma_mle_LMS;