%% LMS
clc;clear;close all
load('pl_robust_test\HY96_powerlaw_robust_1.4_LMS.mat')
Alpha_r = reshape(Alpha,I*J,1);
P_alpha_r = reshape(P_alpha,I*J,1);
Smin2fit_r = reshape(Smin2fit,I*J,1);
Smax2fit_r = reshape(Smax2fit,I*J,1);
[Alpha_rs,Alpha_rs_index] = sort(Alpha_r);
P_alpha_rs = P_alpha_r(Alpha_rs_index);
Smin2fit_rs = Smin2fit_r(Alpha_rs_index);
Smax2fit_rs = Smax2fit_r(Alpha_rs_index);

Tau_r = reshape(Tau,X*Y,1);
P_tau_r = reshape(P_tau,X*Y,1);
Tmin2fit_r = reshape(Tmin2fit,X*Y,1);
Tmax2fit_r = reshape(Tmax2fit,X*Y,1);
Gamma_fit_r = reshape(Gamma_fit,X*Y,1);
Gamma_fit_a_r = reshape(Gamma_fit_a,X*Y,1);
[Tau_rs,Tau_rs_index] = sort(Tau_r);
P_tau_rs = P_tau_r(Tau_rs_index);
Tmin2fit_rs = Tmin2fit_r(Tau_rs_index);
Tmax2fit_rs = Tmax2fit_r(Tau_rs_index);
Gamma_fit_rs = Gamma_fit_r(Tau_rs_index);

II = 0;
for M = 1 : length(Alpha_rs)
    for N = 1 : length(Tau_rs) 
       Gamma_alpha_tau(M,N) = (Tau_rs(N)-1) / (Alpha_rs(M)-1);
       Gamma_fit_1(M,N) = Gamma_fit_rs(N);
       II = II + 1;
       delta_LMS(II,1) = abs(Gamma_alpha_tau(M,N)-Gamma_fit_1(M,N));
    end
end
save('DELTA_LMS.mat','delta_LMS')

for M = 1 : length(Alpha_rs)
    for N = 1 : length(Tau_rs) 
        if P_alpha_rs(M) > 0.1 && P_tau_rs(N) > 0.1
           Gamma_alpha_tau(M,N) = (Tau_rs(N)-1) / (Alpha_rs(M)-1);
           Gamma_fit_1(M,N) = Gamma_fit_rs(N);
           DLAT(M,N) = abs(Gamma_alpha_tau(M,N)-Gamma_fit_1(M,N));
        else
           Gamma_alpha_tau(M,N) = -0.1;
           Gamma_fit_1(M,N) = -0.1;
           DLAT(M,N) = -0.1;
        end
    end
end

AX1 = subplot(3,2,1);
imagesc([30,60],[1,10],Alpha)
xlabel('maximal size S', ...
       'FontName', 'Arial');
ylabel('minimal size S', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\alpha$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,2,2);
imagesc([30,60],[1,10],P_alpha)
xlabel('maximal size S', ...
       'FontName', 'Arial');
ylabel('minimal size S', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('p', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,4);
imagesc([9 20],[1 5],Tau);
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\tau$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,5);
imagesc([9 20],[1 5],P_tau)
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('p', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,6);
imagesc([9 20],[1 5],Gamma_fit)
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\gamma$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');

AX1 = subplot(3,2,5);
Gamma_alpha_tau_1 = Gamma_alpha_tau;
for X = 1 : 310
    for Y = 1 : 60
        if Gamma_alpha_tau(X,Y) >= max(max(Gamma_fit)) + 1
           Gamma_alpha_tau_1(X,Y) = max(max(Gamma_fit)) + 1;
        end
        if Gamma_alpha_tau(X,Y) == -0.1
            Gamma_alpha_tau_1(X,Y) = max(max(Gamma_fit)) + 1.5;
        end
    end
end
imagesc(Gamma_alpha_tau_1)
xticks([1 10 20 30 40 50 60])
xticklabels({num2str(Tau_rs(1)),...
    num2str(Tau_rs(10)),...
    num2str(Tau_rs(20)),...
    num2str(Tau_rs(30)),...
    num2str(Tau_rs(40)),...
    num2str(Tau_rs(50)),...
    num2str(Tau_rs(60))});
yticks([1 50 100 150 200 250 300])
yticklabels({num2str(Alpha_rs(1)),...
    num2str(Alpha_rs(50)),...
    num2str(Alpha_rs(100)),...
    num2str(Alpha_rs(150)),...
    num2str(Alpha_rs(200)),...
    num2str(Alpha_rs(250)),...
    num2str(Alpha_rs(300))});
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
xlabel('$\tau$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
ylabel('$\alpha$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\frac{1-\tau}{1-\alpha}$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,2,6);
N_delta_01 = 0;
for X = 1 : 310
    for Y = 1 : 60
        if DLAT(X,Y) <= 0.1 && DLAT(X,Y)>0
            N_delta_01 = N_delta_01 + 1;
           Delta(X,Y) = DLAT(X,Y);
        end
        if DLAT(X,Y) > 0.1
            Delta(X,Y) = 0.13;
        end
        if DLAT(X,Y) < 0
            Delta(X,Y) = 0.15;
        end
    end
end
imagesc(Delta)
xticks([1 10 20 30 40 50 60])
xticklabels({num2str(Tau_rs(1)),...
    num2str(Tau_rs(10)),...
    num2str(Tau_rs(20)),...
    num2str(Tau_rs(30)),...
    num2str(Tau_rs(40)),...
    num2str(Tau_rs(50)),...
    num2str(Tau_rs(60))});
yticks([1 50 100 150 200 250 300])
yticklabels({num2str(Alpha_rs(1)),...
    num2str(Alpha_rs(50)),...
    num2str(Alpha_rs(100)),...
    num2str(Alpha_rs(150)),...
    num2str(Alpha_rs(200)),...
    num2str(Alpha_rs(250)),...
    num2str(Alpha_rs(300))});
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
xlabel('$\tau$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
ylabel('$\alpha$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$|\frac{1-\tau}{1-\alpha}-\gamma|$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
%% MMS
clc;clear;close all
load('pl_robust_test\HY96_powerlaw_robust_1.4_MMS.mat')
Alpha_r = reshape(Alpha,I*J,1);
P_alpha_r = reshape(P_alpha,I*J,1);
Smin2fit_r = reshape(Smin2fit,I*J,1);
Smax2fit_r = reshape(Smax2fit,I*J,1);
[Alpha_rs,Alpha_rs_index] = sort(Alpha_r);
P_alpha_rs = P_alpha_r(Alpha_rs_index);
Smin2fit_rs = Smin2fit_r(Alpha_rs_index);
Smax2fit_rs = Smax2fit_r(Alpha_rs_index);

Tau_r = reshape(Tau,X*Y,1);
P_tau_r = reshape(P_tau,X*Y,1);
Tmin2fit_r = reshape(Tmin2fit,X*Y,1);
Tmax2fit_r = reshape(Tmax2fit,X*Y,1);
Gamma_fit_r = reshape(Gamma_fit,X*Y,1);
Gamma_fit_a_r = reshape(Gamma_fit_a,X*Y,1);
[Tau_rs,Tau_rs_index] = sort(Tau_r);
P_tau_rs = P_tau_r(Tau_rs_index);
Tmin2fit_rs = Tmin2fit_r(Tau_rs_index);
Tmax2fit_rs = Tmax2fit_r(Tau_rs_index);
Gamma_fit_rs = Gamma_fit_r(Tau_rs_index);

II = 0;
for M = 1 : length(Alpha_rs)
    for N = 1 : length(Tau_rs) 
       Gamma_alpha_tau(M,N) = (Tau_rs(N)-1) / (Alpha_rs(M)-1);
       Gamma_fit_1(M,N) = Gamma_fit_rs(N);
       II = II + 1;
       delta_MMS(II,1) = abs(Gamma_alpha_tau(M,N)-Gamma_fit_1(M,N));
    end
end
save('DELTA_MMS.mat','delta_MMS')

for M = 1 : length(Alpha_rs)
    for N = 1 : length(Tau_rs) 
        if P_alpha_rs(M) > 0.1 && P_tau_rs(N) > 0.1
           Gamma_alpha_tau(M,N) = (Tau_rs(N)-1) / (Alpha_rs(M)-1);
           Gamma_fit_1(M,N) = Gamma_fit_rs(N);
           DLAT(M,N) = abs(Gamma_alpha_tau(M,N)-Gamma_fit_1(M,N));
        else
           Gamma_alpha_tau(M,N) = -0.1;
           Gamma_fit_1(M,N) = -0.1;
           DLAT(M,N) = -0.1;
        end
    end
end

AX1 = subplot(3,2,1);
imagesc([30,60],[1,10],Alpha)
xlabel('maximal size S', ...
       'FontName', 'Arial');
ylabel('minimal size S', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\alpha$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,2,2);
imagesc([30,60],[1,10],P_alpha)
xlabel('maximal size S', ...
       'FontName', 'Arial');
ylabel('minimal size S', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('p', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,4);
imagesc([9 20],[1 5],Tau);
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\tau$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,5);
imagesc([9 20],[1 5],P_tau)
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('p', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,6);
imagesc([9 20],[1 5],Gamma_fit)
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\gamma$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');

AX1 = subplot(3,2,5);
Gamma_alpha_tau_1 = Gamma_alpha_tau;
for X = 1 : 310
    for Y = 1 : 60
        if Gamma_alpha_tau(X,Y) >= max(max(Gamma_fit)) + 1
           Gamma_alpha_tau_1(X,Y) = max(max(Gamma_fit)) + 1;
        end
        if Gamma_alpha_tau(X,Y) == -0.1
            Gamma_alpha_tau_1(X,Y) = max(max(Gamma_fit)) + 1.5;
        end
    end
end
imagesc(Gamma_alpha_tau_1)
xticks([1 10 20 30 40 50 60])
xticklabels({num2str(Tau_rs(1)),...
    num2str(Tau_rs(10)),...
    num2str(Tau_rs(20)),...
    num2str(Tau_rs(30)),...
    num2str(Tau_rs(40)),...
    num2str(Tau_rs(50)),...
    num2str(Tau_rs(60))});
yticks([1 50 100 150 200 250 300])
yticklabels({num2str(Alpha_rs(1)),...
    num2str(Alpha_rs(50)),...
    num2str(Alpha_rs(100)),...
    num2str(Alpha_rs(150)),...
    num2str(Alpha_rs(200)),...
    num2str(Alpha_rs(250)),...
    num2str(Alpha_rs(300))});
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
xlabel('$\tau$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
ylabel('$\alpha$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\frac{1-\tau}{1-\alpha}$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,2,6);
N_delta_01 = 0;
for X = 1 : 310
    for Y = 1 : 60
        if DLAT(X,Y) <= 0.1 && DLAT(X,Y)>0
            N_delta_01 = N_delta_01 + 1;
           Delta(X,Y) = DLAT(X,Y);
        end
        if DLAT(X,Y) > 0.1
            Delta(X,Y) = 0.13;
        end
        if DLAT(X,Y) < 0
            Delta(X,Y) = 0.15;
        end
    end
end
imagesc(Delta)
xticks([1 10 20 30 40 50 60])
xticklabels({num2str(Tau_rs(1)),...
    num2str(Tau_rs(10)),...
    num2str(Tau_rs(20)),...
    num2str(Tau_rs(30)),...
    num2str(Tau_rs(40)),...
    num2str(Tau_rs(50)),...
    num2str(Tau_rs(60))});
yticks([1 50 100 150 200 250 300])
yticklabels({num2str(Alpha_rs(1)),...
    num2str(Alpha_rs(50)),...
    num2str(Alpha_rs(100)),...
    num2str(Alpha_rs(150)),...
    num2str(Alpha_rs(200)),...
    num2str(Alpha_rs(250)),...
    num2str(Alpha_rs(300))});
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
xlabel('$\tau$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
ylabel('$\alpha$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$|\frac{1-\tau}{1-\alpha}-\gamma|$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
%% HMS
clc;clear;close all
load('pl_robust_test\HY96_powerlaw_robust_1.4_HMS.mat')
Alpha_r = reshape(Alpha,I*J,1);
P_alpha_r = reshape(P_alpha,I*J,1);
Smin2fit_r = reshape(Smin2fit,I*J,1);
Smax2fit_r = reshape(Smax2fit,I*J,1);
[Alpha_rs,Alpha_rs_index] = sort(Alpha_r);
P_alpha_rs = P_alpha_r(Alpha_rs_index);
Smin2fit_rs = Smin2fit_r(Alpha_rs_index);
Smax2fit_rs = Smax2fit_r(Alpha_rs_index);

Tau_r = reshape(Tau,X*Y,1);
P_tau_r = reshape(P_tau,X*Y,1);
Tmin2fit_r = reshape(Tmin2fit,X*Y,1);
Tmax2fit_r = reshape(Tmax2fit,X*Y,1);
Gamma_fit_r = reshape(Gamma_fit,X*Y,1);
Gamma_fit_a_r = reshape(Gamma_fit_a,X*Y,1);
[Tau_rs,Tau_rs_index] = sort(Tau_r);
P_tau_rs = P_tau_r(Tau_rs_index);
Tmin2fit_rs = Tmin2fit_r(Tau_rs_index);
Tmax2fit_rs = Tmax2fit_r(Tau_rs_index);
Gamma_fit_rs = Gamma_fit_r(Tau_rs_index);

II = 0;
for M = 1 : length(Alpha_rs)
    for N = 1 : length(Tau_rs) 
       Gamma_alpha_tau(M,N) = (Tau_rs(N)-1) / (Alpha_rs(M)-1);
       Gamma_fit_1(M,N) = Gamma_fit_rs(N);
       II = II + 1;
       delta_HMS(II,1) = abs(Gamma_alpha_tau(M,N)-Gamma_fit_1(M,N));
    end
end
save('DELTA_HMS.mat','delta_HMS')

for M = 1 : length(Alpha_rs)
    for N = 1 : length(Tau_rs) 
        if P_alpha_rs(M) > 0.1 && P_tau_rs(N) > 0.1
           Gamma_alpha_tau(M,N) = (Tau_rs(N)-1) / (Alpha_rs(M)-1);
           Gamma_fit_1(M,N) = Gamma_fit_rs(N);
           DLAT(M,N) = abs(Gamma_alpha_tau(M,N)-Gamma_fit_1(M,N));
        else
           Gamma_alpha_tau(M,N) = -0.1;
           Gamma_fit_1(M,N) = -0.1;
           DLAT(M,N) = -0.1;
        end
    end
end

AX1 = subplot(3,2,1);
imagesc([30,60],[1,10],Alpha)
xlabel('maximal size S', ...
       'FontName', 'Arial');
ylabel('minimal size S', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\alpha$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,2,2);
imagesc([30,60],[1,10],P_alpha)
xlabel('maximal size S', ...
       'FontName', 'Arial');
ylabel('minimal size S', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('p', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,4);
imagesc([9 20],[1 5],Tau);
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\tau$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,5);
imagesc([9 20],[1 5],P_tau)
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('p', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,6);
imagesc([9 20],[1 5],Gamma_fit)
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\gamma$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');

AX1 = subplot(3,2,5);
Gamma_alpha_tau_1 = Gamma_alpha_tau;
for X = 1 : 310
    for Y = 1 : 60
        if Gamma_alpha_tau(X,Y) >= max(max(Gamma_fit)) + 1
           Gamma_alpha_tau_1(X,Y) = max(max(Gamma_fit)) + 1;
        end
        if Gamma_alpha_tau(X,Y) == -0.1
            Gamma_alpha_tau_1(X,Y) = max(max(Gamma_fit)) + 1.5;
        end
    end
end
imagesc(Gamma_alpha_tau_1)
xticks([1 10 20 30 40 50 60])
xticklabels({num2str(Tau_rs(1)),...
    num2str(Tau_rs(10)),...
    num2str(Tau_rs(20)),...
    num2str(Tau_rs(30)),...
    num2str(Tau_rs(40)),...
    num2str(Tau_rs(50)),...
    num2str(Tau_rs(60))});
yticks([1 50 100 150 200 250 300])
yticklabels({num2str(Alpha_rs(1)),...
    num2str(Alpha_rs(50)),...
    num2str(Alpha_rs(100)),...
    num2str(Alpha_rs(150)),...
    num2str(Alpha_rs(200)),...
    num2str(Alpha_rs(250)),...
    num2str(Alpha_rs(300))});
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
xlabel('$\tau$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
ylabel('$\alpha$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\frac{1-\tau}{1-\alpha}$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,2,6);
N_delta_01 = 0;
for X = 1 : 310
    for Y = 1 : 60
        if DLAT(X,Y) <= 0.1 && DLAT(X,Y)>0
            N_delta_01 = N_delta_01 + 1;
           Delta(X,Y) = DLAT(X,Y);
        end
        if DLAT(X,Y) > 0.1
            Delta(X,Y) = 0.13;
        end
        if DLAT(X,Y) < 0
            Delta(X,Y) = 0.15;
        end
    end
end
imagesc(Delta)
xticks([1 10 20 30 40 50 60])
xticklabels({num2str(Tau_rs(1)),...
    num2str(Tau_rs(10)),...
    num2str(Tau_rs(20)),...
    num2str(Tau_rs(30)),...
    num2str(Tau_rs(40)),...
    num2str(Tau_rs(50)),...
    num2str(Tau_rs(60))});
yticks([1 50 100 150 200 250 300])
yticklabels({num2str(Alpha_rs(1)),...
    num2str(Alpha_rs(50)),...
    num2str(Alpha_rs(100)),...
    num2str(Alpha_rs(150)),...
    num2str(Alpha_rs(200)),...
    num2str(Alpha_rs(250)),...
    num2str(Alpha_rs(300))});
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',15);
xlabel('$\tau$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
ylabel('$\alpha$', ...
      'Interpreter','latex',...
       'FontName', 'Arial',...
       'FontSize',20);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$|\frac{1-\tau}{1-\alpha}-\gamma|$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 22, ...
      'FontWeight', 'bold');