clc;clear;close all
addpath('CritAnalysisSoftwarePackage2016-04-25');
figure(...
    'Color', 'w', ...
    'Units', 'Normalized', ...
    'Name', 'Figure 2 Signature of criticality as a function of MS in resting-state brain networks', ...
    'Position', [0.1 0.1 0.8 0.8]);

% figure 2 a
load(['D:\criticality_cognitive\project_synchrony_',...
    'avalanche_fluid_Iq\b_MS_SE_STATIC\MS_SE_HY96_RS.mat'])
[MS_SE_fit] = createFit_poly2(syn(:,1), synE(:,1));
P1 = MS_SE_fit.p1; 
P2 = MS_SE_fit.p2; 
P3 = MS_SE_fit.p3;
F2_a.MS = syn;
F2_a.SE = synE;
F2_a.MSfit = min(syn):0.01:max(syn)+0.01;
F2_a.SEfit = P1 .* (F2_a.MSfit) .^ 2+P2 .* F2_a.MSfit + P3;
AX1 = subplot(3,3,1);
plot(F2_a.MS, F2_a.SE, 'LineStyle', 'none', ...
    'LineWidth', 2, 'color', [0.5,0.5,0.5], ...
    'Marker', 'o', 'MarkerSize', 6);
hold on
F1 = plot(F2_a.MSfit, F2_a.SEfit, 'Color', [1,0,0], ...
    'LineStyle', '--', 'LineWidth', 2.5);
set(gca, 'FontName', 'Arial', 'FontSize', 12);
xlim([0.2,0.7]);
legend(F1, '$fit$', 'Interpreter', 'latex', ...
    'Location', 'northwest', 'FontName', 'Arial', ...
    'FontSize', 15, 'EdgeColor', [1,1,1]);
legend('boxoff')
ylabel('SE H(r)', 'FontName', 'Arial', 'FontSize', 15);
set(gca, 'xtick', [], 'xticklabel', []);
set(gca, 'XColor', 'white');
title('A', 'FontName', 'Arial', 'FontSize', 24,'units', 'normalized', ...
    'position', [-1/18,1+1/18], 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
AX1.LineWidth=2; grid off; box(AX1,'off'); hold off;

AX1=subplot('Position', [0.13 0.58 0.21 0.10]);
histogram(F2_a.MS, 30, ...
    'Normalization', 'probability');
[F2_a.histcount, F2_a.histcenter] = hist(F2_a.MS, 30, ...
    'Normalization', 'probability');
xlim([0.2, 0.7]);
set(gca, 'FontName', 'Arial', 'FontSize', 12);
ylabel('P(<r>)', 'FontName', 'Arial', 'FontSize', 15);
xlabel('MS <r>', 'FontSize', 15);
box(AX1, 'off'); AX1.LineWidth = 2; grid off; hold off;

%% figure 2 b
AX1 = subplot(2,3,2);
load(['D:\criticality_cognitive\project_synchrony_avalanche',...
    '_fluid_Iq\f_avalanche_analysis_above_peak\all_subject_group',...
    '\HY_96\Ava_diff_thd\Avalanches_1.4.mat'], 'BP')
Branching = BP(:, 1);
[MS_branching] = createFit_poly1(syn(:,1), Branching);
[R_syn_bran, P_syn_bran] = corr(syn(:,1), Branching);
B = MS_branching.p1; 
C = MS_branching.p2; 
F2_b.MS = syn(:,1);
F2_b.branching = Branching;
F2_b.MSfit = min(syn(:,1)) : 0.01 : max(syn(:,1)) + 0.01;
F2_b.branchingFit = B .* F2_b.MSfit + C;
F2_b.lineFitR = R_syn_bran;
F2_b.lineFitP = P_syn_bran;
F1 = plot([0.2,0.7], [1,1], 'Color', [0,1,0], ...
    'LineStyle', '--', 'LineWidth', 2.5); 
hold on
plot(F2_b.MS, F2_b.branching, 'Color', [0.50,0.50,0.50], ...
    'color', [0.5,0.5,0.5], 'Marker', 'o', ...
    'MarkerSize', 6, 'LineStyle', 'none', 'LineWidth', 2);
F2=plot(F2_b.MSfit, F2_b.branchingFit, 'Color', [1, 0, 0], ...
    'LineStyle', '--', 'LineWidth', 2.5);
set(gca, 'FontName', 'Arial', 'FontSize', 12);
legend([F1, F2], '$\sigma=1$', '$fit$', ...
    'Interpreter', 'latex', 'Location', 'northwest', ...
    'FontName', 'Arial', 'FontSize', 15, 'EdgeColor', [1,1,1]);
legend('boxoff');
xlabel('MS <r>', 'FontName', 'Arial', 'FontSize', 15);
ylabel('branching \sigma', 'FontName', 'Arial', 'FontSize', 15);
text(0.15, 0.7, ['$R=', num2str(round(F2_b.lineFitR,2)), '$'], ...
    'units', 'normalized', 'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor', 'none');
text(0.15, 0.6, ['$p=', num2str(round(F2_b.lineFitP,2)), '$'], ...
    'units', 'normalized', 'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor', 'none');
title('B', 'FontName', 'Arial', 'FontSize', 24,'units', 'normalized', ...
    'position', [-1/18,1+1/18], 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
AX1.LineWidth=2; grid off; box(AX1,'off'); hold off;


%% figure 2 c
AX1=subplot(2,3,3);
Smax2fit=30; Smin2fit=3; 
load('avalanches_HMS_1.4.mat', 'ava_size_HMS')
S_HMS=ava_size_HMS; 
load('avalanches_MMS_1.4.mat', 'ava_size_MMS')
S_MMS=ava_size_MMS; 
load('avalanches_LMS_1.4.mat', 'ava_size_LMS')
S_LMS=ava_size_LMS; 
[alpha_mle_MMS] = plmle(S_MMS, 'xmin', Smin2fit, 'xmax', Smax2fit);
S_p_MMS = hist(S_MMS,min(S_MMS):max(S_MMS)); 
S_p_HMS = hist(S_HMS, min(S_HMS):max(S_HMS));
S_p_LMS = hist(S_LMS, min(S_LMS):max(S_LMS));
F2_c.referenceSizeFit =  1:200;
F2_c.referenceSizeDistributionFitForLMS =  10.^(log10((1:200).^(-alpha_mle_MMS))-2);
F2_c.referenceSizeDistributionFitForMMS =  10.^(log10((1:200).^(-alpha_mle_MMS))-1);
F2_c.referenceSizeDistributionFitForHMS =  10.^(log10((1:200).^(-alpha_mle_MMS)));
F2_c.SizeRangeLMS =  min(S_LMS):max(S_LMS);
F2_c.SizeRangeMMS =  min(S_MMS):max(S_MMS);
F2_c.SizeRangeHMS =  min(S_HMS):max(S_HMS);
F2_c.SizeDistributionLMS =  S_p_LMS ./ S_p_LMS(1);
F2_c.SizeDistributionMMS =  S_p_MMS ./ S_p_MMS(1);
F2_c.SizeDistributionHMS =  S_p_HMS ./ S_p_HMS(1);
F2_c.alphaMMS =  alpha_mle_MMS;
loglog(F2_c.referenceSizeFit, F2_c.referenceSizeDistributionFitForLMS, ...
    'Color', [0.5,0.5,0.5], 'LineStyle', '--', 'LineWidth', 5);
hold on;
loglog(F2_c.referenceSizeFit, F2_c.referenceSizeDistributionFitForMMS, ...
    'Color', [0.5,0.5,0.5], 'LineStyle', '--', 'LineWidth', 5);
F1=loglog(F2_c.referenceSizeFit, F2_c.referenceSizeDistributionFitForHMS, ...
    'Color', [0.5,0.5,0.5], 'LineStyle', '--', 'LineWidth', 5);
F2 = loglog(F2_c.SizeRangeHMS, F2_c.SizeDistributionHMS, ...
    'Color', [1,0,0], 'LineStyle', 'none', ...
    'LineWidth', 2, 'Marker', 'o', 'MarkerSize', 6);
f3 = loglog(F2_c.SizeRangeMMS, 10 .^ (log10(F2_c.SizeDistributionMMS)-1), ...
    'Color', [0,1,0], 'LineStyle', 'none', 'LineWidth', 2, ...
    'Marker', 'o', 'MarkerSize', 6);
f4 = loglog(F2_c.SizeRangeLMS, 10.^(log10(F2_c.SizeDistributionLMS)-2), ...
    'Color', [0,0,1], 'LineStyle', 'none', ...
    'LineWidth', 2, 'Marker', 'o', 'MarkerSize', 6);
set(gca, 'FontName', 'Arial', 'FontSize', 12)
legend([F1,F2,f3,f4], ...
    ['$\alpha=',num2str(round(alpha_mle_MMS,2)),'$'], '$HMS$', '$MMS$', '$LMS$', ...
    'Interpreter', 'latex', 'Location','northeast', ...
    'FontName', 'Arial', 'FontSize', 15, 'EdgeColor', [1,1,1]);
legend('boxoff');
xlabel('avalanche size S', 'FontName', 'Arial', 'FontSize', 15);
ylabel('P(S)', 'FontName', 'Arial', 'FontSize', 15);
title('C', 'FontName', 'Arial', 'FontSize', 24,'units', 'normalized', ...
    'position', [-1/18,1+1/18], 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
AX1.LineWidth=2; grid off; box(AX1,'off'); hold off;


%% figure 2 d
AX1 = subplot(2,3,4);
Tmax2fit = 9; 
Tmin2fit=2;
load('avalanches_HMS_1.4.mat', 'ava_duration_HMS') 
T_HMS=ava_duration_HMS;
load('avalanches_MMS_1.4.mat', 'ava_duration_MMS') 
T_MMS=ava_duration_MMS;
load('avalanches_LMS_1.4.mat', 'ava_duration_LMS')
T_LMS=ava_duration_LMS;
[tau_mle_MMS] = plmle(T_MMS, ...
    'xmin', Tmin2fit, ...
    'xmax', Tmax2fit);
T_p_HMS = hist(T_HMS, min(T_HMS):max(T_HMS));
T_p_MMS = hist(T_MMS, min(T_MMS):max(T_MMS)); 
T_p_LMS = hist(T_LMS, min(T_LMS):max(T_LMS));
F2_d.referenceDurationFit =  1:42;
F2_d.referenceDurationDistributionFitForLMS =  10.^(log10((1:42).^(-tau_mle_MMS))-2);
F2_d.referenceDurationDistributionFitForMMS =  10.^(log10((1:42).^(-tau_mle_MMS))-1);
F2_d.referenceDurationDistributionFitForHMS =  10.^(log10((1:42).^(-tau_mle_MMS))-0);
F2_d.DurationRangeLMS =  min(T_LMS):max(T_LMS);
F2_d.DurationRangeMMS =  min(T_MMS):max(T_MMS);
F2_d.DurationRangeHMS =  min(T_HMS):max(T_HMS);
F2_d.DurationDistributionLMS =  T_p_LMS ./ T_p_LMS(1);
F2_d.DurationDistributionMMS =  T_p_MMS ./ T_p_MMS(1);
F2_d.DurationDistributionHMS =  T_p_HMS ./ T_p_HMS(1);
F2_d.tauMMS =  tau_mle_MMS;
loglog(F2_d.referenceDurationFit, F2_d.referenceDurationDistributionFitForHMS, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', '--', 'LineWidth',5);
hold on
loglog(F2_d.referenceDurationFit, F2_d.referenceDurationDistributionFitForMMS, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', '--', ...
    'LineWidth', 5);
F1=loglog(F2_d.referenceDurationFit, F2_d.referenceDurationDistributionFitForLMS, ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', '--', ...
    'LineWidth',5);
F2=loglog(F2_d.DurationRangeHMS,F2_d.DurationDistributionHMS, ...
    'Color', [1,0,0], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
f3 = loglog(F2_d.DurationRangeMMS,10.^(log10(F2_d.DurationDistributionMMS)-1), ...
    'Color', [0,1,0], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
f4 = loglog(F2_d.DurationRangeLMS,10.^(log10(F2_d.DurationDistributionLMS)-2), ...
    'Color', [0,0,1], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12)
legend([F1,F2,f3,f4], ...
    ['$\tau=',num2str(round(tau_mle_MMS,2)),'$'], '$HMS$', '$MMS$', '$LMS$',...
    'Interpreter', 'latex', ...
    'Location', 'northeast', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'EdgeColor', [1,1,1]);
legend('boxoff');
xlabel('avalanche duration T', ...
    'FontName', 'Arial', ...
    'FontSize',15)
ylabel('P(T)', ...
    'FontName', 'Arial', ...
    'FontSize', 15)
title('D', 'FontName', 'Arial', 'FontSize', 24,'units', 'normalized', ...
    'position', [-1/18,1+1/18], 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
AX1.LineWidth=2; grid off; box(AX1,'off'); hold off;


%% figure 2 f 
AX1=subplot(2,3,6);
load('avalanches_HMS_1.4.mat', 'Kappa_lzGroup_HMS')
load('avalanches_LMS_1.4.mat', 'Kappa_lzGroup_LMS')
load('avalanches_MMS_1.4.mat', 'Kappa_lzGroup_MMS')
F2_f.m_range = 5:100;
F2_f.Kappa_HMS = Kappa_lzGroup_HMS(5:100);
F2_f.Kappa_MMS = Kappa_lzGroup_MMS(5:100);
F2_f.Kappa_LMS = Kappa_lzGroup_LMS(5:100);
plot(F2_f.m_range,F2_f.Kappa_HMS, ...
    'Color', [1,0,0], ...
    'LineStyle', '-', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 2);
hold on
plot(F2_f.m_range,F2_f.Kappa_MMS, ...
    'Color', [0,1,0], ...
    'LineStyle', '-', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 2);
plot(F2_f.m_range, F2_f.Kappa_LMS, ...
    'Color', [0,0,1], ...
    'LineStyle', '-', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 2);
set(gca,...
    'FontName', 'Arial', ...
    'FontSize', 12);
xlabel('m', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
ylabel('kappa \kappa', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
legend('$HMS$', '$MMS$', '$LMS$', ...
    'Interpreter', 'latex', ...
    'Location', 'southeast', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'EdgeColor', 'none')
title('F', 'FontName', 'Arial', 'FontSize', 24,'units', 'normalized', ...
    'position', [-1/18,1+1/18], 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
AX1.LineWidth=2; grid off; box(AX1,'off'); hold off;
%% figure 2 e
AX1=subplot(2,3,5);
load('avalanches_HMS_1.4.mat', 'gamma_fitHMS')
load('avalanches_HMS_1.4.mat', 'gamma_mle_HMS')
load('avalanches_MMS_1.4.mat', 'gamma_fitMMS')
load('avalanches_MMS_1.4.mat', 'gamma_mle_MMS')
load('avalanches_LMS_1.4.mat', 'gamma_fitLMS')
load('avalanches_LMS_1.4.mat', 'gamma_mle_LMS')
delte_LMS = abs(gamma_fitLMS-gamma_mle_LMS);
delte_MMS = abs(gamma_fitMMS-gamma_mle_MMS);
delte_HMS = abs(gamma_fitHMS-gamma_mle_HMS);
F2_e.group{1,1} = 'LMS'; 
F2_e.group{2,1} = 'MMS'; 
F2_e.group{3,1} = 'HMS'; 
F2_e.gamma_fit = [gamma_fitLMS, gamma_fitMMS, gamma_fitHMS];
F2_e.gamma_alpha_tau = [gamma_mle_LMS, gamma_mle_MMS, gamma_mle_HMS];
F2_e.delte = [delte_LMS, delte_MMS, delte_HMS];
plot([1,2,3], F2_e.gamma_fit, ...
    'LineStyle', '-', ...
    'LineWidth', 2, ...
    'Color', [0,0.5,1], ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on
plot([1,2,3], F2_e.gamma_alpha_tau, ...
    'LineStyle', '-', ...
    'LineWidth', 2, ...
    'Color', [0.5,0,1], ...
    'Marker', 'o', ...
    'MarkerSize', 6);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12);
xlabel('subject groups', ...
    'FontName', 'Arial', ...
    'FontSize',15);
ylabel('scaling relation', ...
    'FontName', 'Arial', ...
    'FontSize',15);
xlim([0.8,3.2]); 
set(gca,'XTick',[1,2,3]); 
set(gca,'xticklabel',{'LMS','MMS','HMS'});

legend('$\gamma$', '$\frac{1-\tau}{1-\alpha}$', ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontName', 'Arial', ...
    'FontSize', 18, ...
    'EdgeColor', 'none')
legend('boxoff')
title('E', 'FontName', 'Arial', 'FontSize', 24,'units', 'normalized', ...
    'position', [-1/18,1+1/18], 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
AX1.LineWidth=2; grid off; box(AX1,'off'); hold off;

AX1 = axes('position',[0.5 0.15 0.07 0.10]);
plot([1,2,3], F2_e.delte, ...
    'LineStyle', '-', ...
    'LineWidth', 1.5, ...
    'Color', [0,0,0], ...
    'Marker', 'o', ...
    'MarkerSize', 3);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 12);
set(gca, ...
    'XTick', [1,2,3]); 
set(gca, ...
    'xticklabel', {'LMS','MMS','HMS'});
ylabel('\delta', ...
    'FontName', 'Arial', ...
    'FontSize',15);
xlim([0.8,3.2]);
box(AX1,'off'); 
AX1.LineWidth=2; 
grid off; 
hold off;
%% save
save('Figure_2.mat', 'F2_a', 'F2_b', 'F2_c', 'F2_d', 'F2_e', 'F2_f')