%% display power law robust
clc;clear;close all
load('z_1024\Z1024_powerlaw_robust_3.4_allsubject.mat');
Alpha_r = reshape(Alpha,I*J,1);
P_alpha_r = reshape(P_alpha,I*J,1);
Smin2fit_r = reshape(Smin2fit,I*J,1);
Smax2fit_r = reshape(Smax2fit,I*J,1);
Alpha_rc = Alpha_r(find(P_alpha_r>0.1));
[Alpha_rc,Alpha_rc_index] = sort(Alpha_rc);
P_alpha_rc = P_alpha_r(find(P_alpha_r>0.1));
P_alpha_rc = P_alpha_rc(Alpha_rc_index);
Smin2fit_rc = Smin2fit_r(find(P_alpha_r>0.1));
Smin2fit_rc = Smin2fit_rc(Alpha_rc_index);
Smax2fit_rc =Smax2fit_r(find(P_alpha_r>0.1));
Smax2fit_rc = Smax2fit_rc(Alpha_rc_index);

Tau_r = reshape(Tau,X*Y,1);
P_tau_r = reshape(P_tau,X*Y,1);
Tmin2fit_r = reshape(Tmin2fit,X*Y,1);
Tmax2fit_r = reshape(Tmax2fit,X*Y,1);
Gamma_fit_r = reshape(Gamma_fit,X*Y,1);
Gamma_fit_a_r = reshape(Gamma_fit_a,X*Y,1);
Tau_rc = Tau_r(find(P_tau_r>0.1));
[Tau_rc,Tau_rc_index] = sort(Tau_rc);
P_tau_rc = P_tau_r(find(P_tau_r>0.1));
P_tau_rc = P_tau_rc(Tau_rc_index);
Tmin2fit_rc = Tmin2fit_r(find(P_tau_r>0.1));
Tmin2fit_rc = Tmin2fit_rc(Tau_rc_index);
Tmax2fit_rc = Tmax2fit_r(find(P_tau_r>0.1));
Tmax2fit_rc = Tmax2fit_rc(Tau_rc_index);
Trange(1,:) = Tmin2fit_rc;
Trange(2,:) = Tmax2fit_rc;
Gamma_fit_rc = Gamma_fit_r(find(P_tau_r>0.1));
Gamma_fit_rc = Gamma_fit_rc(Tau_rc_index);
Gamma_fit_a_rc = Gamma_fit_a_r(find(P_tau_r>0.1));
Gamma_fit_a_rc = Gamma_fit_a_rc(Tau_rc_index);

for M = 1 : length(Alpha_rc)
    for N = 1 : length(Tau_rc) 
        Gamma_alpha_tau(M,N) = (Tau_rc(N)-1) / (Alpha_rc(M)-1);
        Gamma_fit_1(M,N) = Gamma_fit_rc(N);
    end
end
DLAT = abs(Gamma_alpha_tau-Gamma_fit_1);

AX1 = subplot(3,2,1);
imagesc([30,60],[1,10],Alpha)
xlabel('maximal size S', ...
       'FontName', 'Arial');
ylabel('minimal size S', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',13);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\alpha$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 18, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,2,2);
imagesc([30,60],[1,10],P_alpha)
xlabel('maximal size S', ...
       'FontName', 'Arial');
ylabel('minimal size S', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',13);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('P', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 18, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,4);
imagesc([9 20],[1 5],Tau);
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',13);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\tau$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 18, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,5);
imagesc([9 20],[1 5],P_tau)
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',13);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('P', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 18, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,6);
imagesc([9 20],[1 5],Gamma_fit)
xlabel('maximal duration T', ...
       'FontName', 'Arial');
ylabel('minimal duration T', ...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',13);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\gamma$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 18, ...
      'FontWeight', 'bold');

AX1 = subplot(3,2,5);
Gamma_alpha_tau_1 = Gamma_alpha_tau;
for X = 1 : 247
    for Y = 1 : 16
        if Gamma_alpha_tau(X,Y) >= max(max(Gamma_fit))+2
           Gamma_alpha_tau_1(X,Y) = max(max(Gamma_fit))+2;
        end
    end
end
imagesc(Gamma_alpha_tau_1)
% xticks(1:1:8)
% xticklabels({num2str(Tau_rc(1)),...
%     num2str(Tau_rc(2)),...
%     num2str(Tau_rc(3)),...
%     num2str(Tau_rc(4)),...
%     num2str(Tau_rc(5)),...
%     num2str(Tau_rc(6)),...
%     num2str(Tau_rc(7)),...
%     num2str(Tau_rc(8))});
% yticks([1 50 100 150 200])
% yticklabels({num2str(Alpha_rc(1)),num2str(Alpha_rc(50)),num2str(Alpha_rc(100)),...
%      num2str(Alpha_rc(150)),num2str(Alpha_rc(200))});
xlabel('$\tau$', ...
      'Interpreter','latex',...
       'FontName', 'Arial');
ylabel('$\alpha$', ...
      'Interpreter','latex',...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',13);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$\frac{1-\tau}{1-\alpha}$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 18, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,2,6);
Num_delta_01 = 0;
for X = 1 : 247
    for Y = 1 : 16
        if DLAT(X,Y) <= 0.1
            Num_delta_01 = Num_delta_01 + 1;
           Delta(X,Y) = DLAT(X,Y);
        end
        if DLAT(X,Y) > 0.1
            Delta(X,Y) = 0.15;
        end
    end
end
imagesc(Delta)
% xticks(1:1:8)
% xticklabels({num2str(Tau_rc(1)),...
%     num2str(Tau_rc(2)),...
%     num2str(Tau_rc(3)),...
%     num2str(Tau_rc(4)),...
%     num2str(Tau_rc(5)),...
%     num2str(Tau_rc(6)),...
%     num2str(Tau_rc(7)),...
%     num2str(Tau_rc(8))});
% yticks([1 50 100 150 200])
% yticklabels({num2str(Alpha_rc(1)),num2str(Alpha_rc(50)),num2str(Alpha_rc(100)),...
%      num2str(Alpha_rc(150)),num2str(Alpha_rc(200))});
xlabel('$\tau$', ...
      'Interpreter','latex',...
       'FontName', 'Arial');
ylabel('$\alpha$', ...
      'Interpreter','latex',...
       'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
     'FontSize',13);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('$|\frac{1-\tau}{1-\alpha}-\gamma|$', ...
      'Interpreter','latex',...
      'FontName','Arial', ...
      'FontSize', 18, ...
      'FontWeight', 'bold');