function [Avalanche, Criterion, BranchingParameter] = CriticalAnalysis_powerlaw(AvaDuration, AvaSize, BinEvent,SizeFitRange, DurationFitRange)
%UNTITLED4 此处显示有关此函数的摘要
%   此处显示详细说明
addpath('D:\supplyment_dataANDcode\z_function\CritAnalysisSoftwarePackage2016-04-25')
%% the step one: average size across avalanche with same lifetime
[Lifetime, AverageSize]=lifetimeAverageSize(AvaDuration, AvaSize);
%% the step two: calculate the distribution of avalanche size and duration
    SizeRange = min(AvaSize) : 1 : max(AvaSize);
    AvaSizeHist = hist(AvaSize, SizeRange);
    AvaSizeHist = AvaSizeHist/AvaSizeHist(1);
    
    DurationRange = min(AvaDuration) : 1 : max(AvaDuration);
    AvaDurationHist = hist(AvaDuration,DurationRange);
    AvaDurationHist = AvaDurationHist/AvaDurationHist(1);
%% the step three: power law fit
    [Alpha, Smin2fit, Smax2fit] = plmle(AvaSize, 'xmin', SizeFitRange(1), 'xmax', SizeFitRange(2));
    [P_alpha] = pvcalc(AvaSize, Alpha, 'xmin',Smin2fit,'xmax',Smax2fit);
    SizePLFitRange = Smin2fit:Smax2fit;
    SizePLFitDistribution = (Smin2fit:Smax2fit).^(-Alpha);

    [Tau, Tmin2fit, Tmax2fit] = plmle(AvaDuration,'xmin', DurationFitRange(1), 'xmax', DurationFitRange(2));
    [P_tau] = pvcalc(AvaDuration, Tau, 'xmin',Tmin2fit,'xmax',Tmax2fit);
    DurationPLFitRange = Tmin2fit:Tmax2fit;
    DurationPLFitDistribution = (Tmin2fit:Tmax2fit).^(-Tau);
        
    [Gamma_nlsfit] = createFit_pl_nonlinearLS(Lifetime(Tmin2fit:Tmax2fit), AverageSize(Tmin2fit:Tmax2fit));
    Gamma_fit = Gamma_nlsfit.b;
    Gamma_alpga_tau = (Tau-1) / (Alpha-1);
    LifetimeFitRange = Tmin2fit:Tmax2fit;
    AverageSizeFit = (Gamma_nlsfit.a).*(Tmin2fit:Tmax2fit).^(Gamma_fit);
%% the step four: branching parameter
        EN=0;
        ratio_1=0;
        for I = 1:length(BinEvent)-1
            if BinEvent(I,1) >0
               EN=EN+1;
               ratio_1(EN,1) = BinEvent(I+1,1) ./ BinEvent(I,1);
            end
        end
        BranchingParameter.EventBigThan0=mean(ratio_1);
        
        EN=0;
        ratio_2=0;
        for I = 1:length(BinEvent)-1
            if BinEvent(I,1) == 1
               EN=EN+1;
               ratio_2(EN,1) = BinEvent(I+1,1) ./ BinEvent(I,1);
            end
        end
        BranchingParameter.EventEqual1=mean(ratio_2);
        
        EN=0;
        ratio_3=0;
        for I = 2:length(BinEvent)-1
            if BinEvent(I,1) >0 && BinEvent(I-1,1) == 0
               EN=EN+1;
               ratio_3(EN,1) = BinEvent(I+1,1) ./ BinEvent(I,1);
            end
        end
        BranchingParameter.EventBigThan0_onlytwo = mean(ratio_3);
        
        EN=0;
        ratio_4=0;
        for I = 2:length(BinEvent)-1
            if BinEvent(I,1) ==1 && BinEvent(I-1,1) == 0
               EN=EN+1;
               ratio_4(EN,1) = BinEvent(I+1,1) ./ BinEvent(I,1);
            end
        end
        BranchingParameter.EventEqual1_onlytwo = mean(ratio_4);
        
    % the output
    Avalanche.Size = AvaSize;
    Avalanche.Duration = AvaDuration;
    Avalanche.SizeRange = SizeRange;
    Avalanche.AvaSizeHist = AvaSizeHist;
    Avalanche.DurationRange = DurationRange;
    Avalanche.AvaDurationHist = AvaDurationHist;
    Avalanche.Lifetime = Lifetime;
    Avalanche.AverageSize = AverageSize;
    
    Criterion.Alpha = Alpha;
    Criterion.P_alpha = P_alpha;
    Criterion.SizePLFitRange = SizePLFitRange;
    Criterion.SizePLFitDistribution = SizePLFitDistribution;
    Criterion.Tau = Tau;
    Criterion.P_tau = P_tau;
    Criterion.DurationPLFitRange = DurationPLFitRange;
    Criterion.DurationPLFitDistribution = DurationPLFitDistribution;
    Criterion.Gamma_fit = Gamma_fit;
    Criterion.Gamma_alpga_tau = Gamma_alpga_tau;
    Criterion.LifetimeFitRange = LifetimeFitRange;
    Criterion.AverageSizeFit = AverageSizeFit;
    
%% The second part of avalanche analysis: plot the distribution of avalanche size and duration
    figure(...
      'Color', 'w', ...
      'Units', 'Normalized', ...
      'Name',  'Power law analysis', ...
      'Position', [0.1 0.3 0.8 0.5]);
  
    ax1 = subplot(1,3,1);
    loglog(SizeRange, AvaSizeHist, ...
    'Color', [0.50, 0.50, 0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize',6);
    hold on;
    loglog(SizePLFitRange, SizePLFitDistribution, ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth',2.5);
    text(0.75, 0.8, ...
         ['$\alpha= ', num2str(round(Alpha, 2)), '$'], ...
         'units', 'normalized', ...
         'Interpreter','latex', ...
         'Color', [0.00,0.00,0.00], ...
         'FontName', 'Arial', ...
         'FontSize', 20, ...
         'EdgeColor','none');
    text(0.75, 0.7, ...
         ['$p= ', num2str(round(P_alpha, 2)), '$'], ...
         'units', 'normalized', ...
         'Interpreter','latex',...
         'Color', [0.00,0.00,0.00], ...
         'FontName', 'Arial', ...
         'FontSize', 20, ...
         'EdgeColor','none');
     xlabel('avalanche size S', ...
            'FontName', 'Arial');
     ylabel('P(S)', ...
            'FontName', 'Arial');
     set(gca, ...
         'FontName', 'Arial', ...
         'FontSize',18, ...
         'XTick', [1,10,100,1000], ...
         'YTick', [0.00001,0.0001,0.001,0.01,0.1,1]);
     grid off; 
     ax1.LineWidth = 2; 
     box(ax1,'off'); 
     hold off
     title('A', ...
           'FontName','Arial', ...
           'FontSize', 24, ...
           'FontWeight', 'bold', ....
           'units', 'normalized', ...
           'position', [-1/36,1+1/50], ...
           'HorizontalAlignment', 'right', ...
           'VerticalAlignment','bottom');

      ax1 = subplot(1,3,2);
      loglog(DurationRange, AvaDurationHist, ...
             'Color', [0.50,0.50,0.50], ...
             'LineStyle', 'none', ...
             'LineWidth', 2, ...
             'Marker', 'o', ...
             'MarkerSize',6);
      hold on;
      loglog(DurationPLFitRange, DurationPLFitDistribution, ...
             'Color', [0,1,0], ...
             'LineStyle', '--', ...
             'LineWidth',2.5);
      text(0.75, 0.8, ...
           ['$\tau= ',num2str(round(Tau, 2)),'$'], ...
            'units', 'normalized', ...
            'Interpreter','latex', ...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor','none');
      text(0.75, 0.7, ...
           ['$p= ',num2str(round(P_tau, 2)),'$'], ...
            'units', 'normalized', ...
            'Interpreter','latex',...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor', 'none');
      xlabel('avalanche duration T', ...
             'FontName', 'Arial');
      ylabel('P(T)', ...
             'FontName', 'Arial');
      set(gca, ...
          'FontName', 'Arial', ...
          'FontSize',18, ...
          'XTick',[1,10,100,1000], ...
          'YTick',[0.00001,0.0001,0.001,0.01,0.1,1]);
      title('B', ...
            'FontName', 'Arial', ...
            'FontSize', 24, ...
            'FontWeight', 'bold', ...
            'units', 'normalized', ...
            'position',[-1/36,1+1/50], ...
            'HorizontalAlignment', 'right', ...
            'VerticalAlignment', 'bottom');
      grid off; 
      ax1.LineWidth = 2; 
      box(ax1,'off'); 
      hold off

      ax1 = subplot(1,3,3);
      loglog(Lifetime, AverageSize, ...
             'Color', [0.5,0.5,0.5], ...
             'LineStyle', 'none', ...
             'LineWidth', 2, ...
             'Marker', 'o', ...
             'MarkerSize',6);
      hold on
      loglog(LifetimeFitRange, AverageSizeFit, ...
             'Color', [0,1,0], ...
             'LineStyle', '--', ...
             'LineWidth',2.5);
      text(0.3, 0.8, ...
           ['$\frac{1-\tau}{1-\alpha}= ', num2str(round(Gamma_alpga_tau,2)), '$'], ...
           'units', 'normalized', ...
           'Interpreter', 'latex', ...
           'Color', [0.00,0.00,0.00], ...
           'FontName', 'Arial', ...
           'FontSize', 20, ...
           'EdgeColor', 'none');
      text(0.3, 0.7, ...
           ['$\gamma = ',num2str(round(Gamma_fit,2)), '$'], ...
            'units', 'normalized', ...
            'Interpreter', 'latex', ...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor', 'none');
      xlabel('duration T', ...
             'FontName', 'Arial');
      ylabel('average size', ...
             'FontName', 'Arial');
      set(gca, ...
             'FontName', 'Arial', ...
             'FontSize', 18);
      title('C', ...
            'FontName', 'Arial', ...
            'FontSize', 24, ...
            'units', 'normalized', ...
            'FontWeight', 'bold', ...
            'position', [-1/36,1+1/50], ...
            'HorizontalAlignment', 'right', ...
            'VerticalAlignment', 'bottom');
      box(ax1, 'off'); 
      ax1.LineWidth = 2; 
      grid off; 
      hold off
end

