%% plot the event point figure of HY-96
clc;clear;close all
figure(...
      'Color', 'w', ...
      'Units', 'Normalized', ...
      'Name',  'Event PLOT', ...
      'Position', [0.1 0.3 0.5 0.5]);

load('HY_96\HY96_above_event_2.7.mat');% load the data of event
load('D:\supplyment_dataANDcode\c_MS_SE_static\MS_SE_HY96_RS.mat', 'syn');%load the data of synchronize
[MS_sorted, Index_MS_sorted] = sort(syn); % rank the mean synchronize
LMS(:,1) = MS_sorted(1:20,1);
LMS(:,2) = Index_MS_sorted(1:20,1);
MMS(:,1) = MS_sorted(201:220,1);
MMS(:,2) = Index_MS_sorted(201:220,1);
HMS(:,1) = MS_sorted(276:295,1);
HMS(:,2) = Index_MS_sorted(276:295,1);

AX1 = subplot(3,3,1);
plot(Event_serise{91,1}(:,2),Event_serise{91,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,96]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_9_6 MS=0.2394', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');

AX1 = subplot(3,3,4);
plot(Event_serise{85,1}(:,2),Event_serise{85,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,96]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_9_6 MS=0.4983', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');
  
AX1 = subplot(3,3,7);
plot(Event_serise{166,1}(:,2),Event_serise{166,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,96]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_9_6 MS=0.6866', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');

clear;
load('BN_246\BN246_above_event_3.mat');% load the data of event
load('D:\supplyment_dataANDcode\c_MS_SE_static\MS_SE_HY96_RS.mat', 'syn');%load the data of synchronize
[MS_sorted, Index_MS_sorted] = sort(syn); % rank the mean synchronize
LMS(:,1) = MS_sorted(1:20,1);
LMS(:,2) = Index_MS_sorted(1:20,1);
MMS(:,1) = MS_sorted(201:220,1);
MMS(:,2) = Index_MS_sorted(201:220,1);
HMS(:,1) = MS_sorted(276:295,1);
HMS(:,2) = Index_MS_sorted(276:295,1);
load('D:\supplyment_dataANDcode\c_MS_SE_static\MS_SE_BA246_RS.mat', 'syn')
AX1 = subplot(3,3,2);
plot(Event_serise{91,1}(:,2),Event_serise{91,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,246]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_2_4_6 MS=0.1873', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');

AX1 = subplot(3,3,5);
plot(Event_serise{85,1}(:,2),Event_serise{85,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,246]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_2_4_6 MS=0.4263', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');

AX1 = subplot(3,3,8);
plot(Event_serise{166,1}(:,2),Event_serise{166,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,246]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_2_4_6 MS=0.5853', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');
%
clear;
load('z_1024\Z1024_above_event_3.6.mat');% load the data of event
load('D:\supplyment_dataANDcode\c_MS_SE_static\MS_SE_HY96_RS.mat', 'syn');%load the data of synchronize
[MS_sorted, Index_MS_sorted] = sort(syn); % rank the mean synchronize
LMS(:,1) = MS_sorted(1:20,1);
LMS(:,2) = Index_MS_sorted(1:20,1);% 91
MMS(:,1) = MS_sorted(201:220,1);
MMS(:,2) = Index_MS_sorted(201:220,1);% 85
HMS(:,1) = MS_sorted(276:295,1);
HMS(:,2) = Index_MS_sorted(276:295,1);% 166
load('D:\supplyment_dataANDcode\c_MS_SE_static\MS_SE_Z1024_RS.mat', 'syn')

AX1 = subplot(3,3,3);
plot(Event_serise{91,1}(:,2),Event_serise{91,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,1024]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_1_0_2_4 MS=0.1241', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');

AX1 = subplot(3,3,6);
plot(Event_serise{85,1}(:,2),Event_serise{85,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,1024]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_1_0_2_4 MS=0.3331', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');
AX1 = subplot(3,3,9);
plot(Event_serise{166,1}(:,2),Event_serise{166,1}(:,1),'b.')
xlabel('time (vol.)', ...
            'FontName', 'Arial');
ylabel('ROI', ...
            'FontName', 'Arial');
xlim([0,1200]);
ylim([0,1024]);
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize',18);
grid off; 
AX1.LineWidth = 2; 
box(AX1,'off'); 
hold off
title('Atlas_1_0_2_4 MS=0.5011', ...
      'FontName','Arial', ...
      'FontSize', 20, ...
      'FontWeight', 'bold');