%% BN246
% the powerlaw fit
clc; clear; close all
I_T = 0;
for thr = 1:0.1:2.8
    I_T =I_T + 1;
    load(['BN_246_1\Avalanches_',num2str(thr),'.mat'])
    SizeFitRange = [7,40];
    DurationFitRange = [3,10];
    [Avalanche(I_T), Criterion(I_T), BP_GROUP(I_T)] = ....
        CriticalAnalysis_powerlaw(AvaD_AllSubject, ...
        AvaS_AllSubject, BinE_AllSubject, SizeFitRange, DurationFitRange);
end
thr = 1:0.1:2.8;
save('ava_fit_different_thr\BN246.mat',...
    'Avalanche','Criterion','BP_GROUP','thr');
%% Z1024
% the powerlaw fit
clc; clear; close all
I_T = 0;
for thr = 1:0.1:2.9
    I_T =I_T + 1;
    load(['Z_1024\Z_1024_1\Avalanches_',num2str(thr),'.mat'])
    SizeFitRange = [4,60];
    DurationFitRange = [4,10];
    [Avalanche(I_T), Criterion(I_T), BP_GROUP(I_T)] = ....
        CriticalAnalysis_powerlaw(AvaD_AllSubject, ...
        AvaS_AllSubject, BinE_AllSubject, SizeFitRange, DurationFitRange);
end
thr = 1:0.1:2.9;
save('ava_fit_different_thr\Z1024.mat',...
    'Avalanche','Criterion','BP_GROUP','thr');
%%
clc;clear;close all
%bn246
load('ava_fit_different_thr\BN246.mat')
for S = 1:19
    bpGroup(S) = BP_GROUP(S).EventBigThan0;
    alpha_mle(S) = Criterion(S).Alpha;
end
AX1 = subplot(1,2,1);
plot(bpGroup(4:2:12),alpha_mle(4:2:12), ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on
plot([0.6,1.2], [1.5,1.5], ...
    'Color', [0,0,1], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'none', ...
    'MarkerSize', 6);
plot([1,1], [1.3,1.9], ...
    'Color', [0,0,1], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'none', ...
    'MarkerSize',6);
text(bpGroup(4)+0.01, alpha_mle(4)+0.03, ...
    '$1.3\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(6)+0.01, alpha_mle(6)+0.03, ...
    '$1.5\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(8)+0.01, alpha_mle(8)+0.03, ...
    '$1.7\ SD$', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(10)+0.01, alpha_mle(10)+0.03, ...
    '$1.9\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
text(bpGroup(12)+0.01, alpha_mle(12)+0.03, ...
    '$2.1\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
xlabel('branching \sigma', ...
    'FontName', 'Arial');
ylabel('\alpha', ...
    'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 18);
title('a', 'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units','normalized', ...
    'position',[-1/18,1+1/50], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
box(AX1,'off'); 
AX1.LineWidth=2; 
grid off; 
hold off
clear
%Z1024 
load('ava_fit_different_thr\Z1024.mat')
for S = 1:20
    bpGroup(S) = BP_GROUP(S).EventBigThan0;
    alpha_mle(S) = Criterion(S).Alpha;
end
AX1 = subplot(1,2,2);
plot(bpGroup(7:2:15),alpha_mle(7:2:15), ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on
plot([0.6,1.2], [1.5,1.5], ...
    'Color', [0,0,1], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'none', ...
    'MarkerSize', 6);
plot([1,1], [1.3,1.8], ...
    'Color', [0,0,1], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'none', ...
    'MarkerSize',6);
text(bpGroup(7)+0.01, alpha_mle(7)+0.03, ...
    '$1.6\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(9)+0.01, alpha_mle(9)+0.03, ...
    '$1.8\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(11)+0.01, alpha_mle(11)+0.03, ...
    '$2.0\ SD$', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(13)+0.01, alpha_mle(13)+0.03, ...
    '$2.2\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
text(bpGroup(15)+0.01, alpha_mle(15)+0.03, ...
    '$2.4\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
xlabel('branching \sigma', ...
    'FontName', 'Arial');
ylabel('\alpha', ...
    'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 18);
title('b', 'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units','normalized', ...
    'position',[-1/18,1+1/50], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
box(AX1,'off'); 
AX1.LineWidth=2; 
grid off; 
hold off