clc;clear;close all
addpath('CritAnalysisSoftwarePackage2016-04-25')
figure(...
      'Color', 'w', ...
      'Units', 'Normalized', ...
      'Name', 'Figure 1', ...
      'Position', [0.1 0.1 0.8 0.8]);
  
Thd = 1.4;
%% figure 1 a
load('ROI_signals\HY_96\sub1.mat'); 
%load the ROI signals
Signals_original = rest_HY96_ROI;
% z-normailiez 
Signal_normalized = z_normalize(Signals_original);% z-normalize the roi signals
[~,Event] = eventProduce(Signal_normalized,Thd); % define the avalanche event
F1_a.timePoints = [1:1200]';
F1_a.signal = Signal_normalized(1:1200, 5);
F1_a.threshold = Thd * ones(1200,1);
F1_a.event = Event(1:1200,5);

AX1=subplot(2,3,[1,2]);
F1 = plot(F1_a.timePoints, F1_a.signal, ...
     'Color', [0.5,0.5,0.5], 'LineStyle', '-', 'LineWidth', 1);
hold on
F2 = plot(F1_a.timePoints, F1_a.threshold, ...
     'Color', [0,1,0], 'LineStyle', '--', 'LineWidth', 1);
F3 =  plot(find(F1_a.event>0),3.5*ones(length(find(Event(1:1200,5)>0))),...
     'Color', [1,0,0], 'LineStyle', 'none', 'LineWidth', 1, ...
     'Marker', 'v', 'MarkerSize', 8);
legend({'BOLD','threshold','events'},'Location','southwest', ...
    'FontName','Arial','FontSize',15,'EdgeColor',[1,1,1])
xlabel('time (vol.)', 'FontName', 'Arial');
ylabel('BOLD', 'FontName', 'Arial');
set(gca, 'FontName', 'Arial', 'FontSize', 18);
grid off; AX1.LineWidth = 2; box(AX1, 'off'); hold off
title('A', 'FontName', 'Arial', 'FontSize', 24, ...
    'units', 'normalized', 'position', [-1/36,1+1/18], ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom');

%% figure 1 b 
load(['HY_96\Ava_diff_thd\Avalanches_',num2str(Thd),'.mat'], 'AvaS_AllSubject')
S=AvaS_AllSubject;
Smax2fit=30; Smin2fit=3;
AX1 = subplot(2,3,3);
S_p = hist(S,min(S):max(S));
[Alpha_mle, Smin2fit, Smax2fit] = plmle(S,'xmin',Smin2fit,'xmax',Smax2fit);
[P_alpha_mle] = pvcalc(S, Alpha_mle, 'xmin',Smin2fit,'xmax',Smax2fit);
F1_b.sizeRange = min(S):max(S);
F1_b.sizeDistribution = S_p./S_p(1);
F1_b.alpha = Alpha_mle;
F1_b.p_mle = P_alpha_mle;
F1_b.sizePLFitRange = Smin2fit:Smax2fit;
F1_b.sizePLFitDistribution = (Smin2fit:Smax2fit).^(-Alpha_mle);

F1 = loglog(F1_b.sizeRange, F1_b.sizeDistribution, ...
    'Color', [0.50, 0.50, 0.50], 'LineStyle', 'none', 'LineWidth', 2, ...
    'Marker', 'o', 'MarkerSize',6);
hold on;
load('HY_96_surrogate\noFC\noFC_avalanche_analysis.mat', ...
    'Avalanche_surrogate_nofc')
F2 = loglog(Avalanche_surrogate_nofc.SizeRange,...
    Avalanche_surrogate_nofc.AvaSizeHist,...
    'Color', [0.7,0.7,0.7], 'LineStyle', 'none', 'LineWidth', 1, ...
    'Marker', '<', 'MarkerSize',6);
clear Avalanche_surrogate_nofc
F3 = loglog(F1_b.sizePLFitRange, F1_b.sizePLFitDistribution, ...
    'Color', [0,1,0], 'LineStyle', '--', 'LineWidth',2.5);
text(0.55, 0.8, ...
    ['$\alpha= ', num2str(round(F1_b.alpha, 2)), '$'], ...
    'units', 'normalized', 'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor','none');
text(0.55, 0.7, ...
    ['$p= ', num2str(round(F1_b.p_mle, 2)), '$'], ...
    'units', 'normalized', 'Interpreter','latex',...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor','none');
legend([F1,F2,F3],{'real data','surrogate data','fit'},'Location','southwest',...
    'FontName','Arial','FontSize',15,'EdgeColor',[1,1,1])
legend('boxoff')
xlabel('avalanche size S', 'FontName', 'Arial');
ylabel('P(S)', 'FontName', 'Arial');
set(gca, 'FontName', 'Arial', 'FontSize',18, ...
    'XTick', [1,10,100,1000], 'YTick', [0.00001,0.0001,0.001,0.01,0.1,1]);
grid off; AX1.LineWidth = 2; box(AX1,'off'); hold off
title('B', 'FontName', 'Arial', 'FontSize', 24, ...
    'units', 'normalized', 'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom');

%% figure 1 c
load(['HY_96\Ava_diff_thd\Avalanches_',num2str(Thd),'.mat'], 'AvaD_AllSubject')
T = AvaD_AllSubject;
Tmax2fit = 9; Tmin2fit = 3;
AX1 = subplot(2,3,4);
T_p = hist(T,min(T):max(T));
[Tau_mle, Tmin2fit, Tmax2fit] = plmle(T,'xmin',Tmin2fit,'xmax',Tmax2fit);
[P_tau_mle] = pvcalc(T, Tau_mle, 'xmin',Tmin2fit,'xmax',Tmax2fit);
F1_c.durationRange = min(T):max(T);
F1_c.drationDistribution = T_p / T_p(1);
F1_c.durationPLFitRange = Tmin2fit:Tmax2fit;
F1_c.drationPLFitDistribution = (Tmin2fit:Tmax2fit).^(-Tau_mle);
F1_c.tau = Tau_mle;
F1_c.p_mle = P_tau_mle;

F1 = loglog(F1_c.durationRange, F1_c.drationDistribution, ...
    'Color', [0.50,0.50,0.50], 'LineStyle', 'none', 'LineWidth', 2, ...
    'Marker', 'o', 'MarkerSize',6);
hold on;
load('HY_96_surrogate\noFC\noFC_avalanche_analysis.mat', ...
    'Avalanche_surrogate_nofc')
F2 = loglog(Avalanche_surrogate_nofc.DurationRange,...
    Avalanche_surrogate_nofc.AvaDurationHist,...
    'Color', [0.7,0.7,0.7], 'LineStyle', 'none', 'LineWidth', 1, ...
    'Marker', '<', 'MarkerSize',6);
clear Avalanche_surrogate_nofc
F3 = loglog(F1_c.durationPLFitRange, F1_c.drationPLFitDistribution, ...
    'Color', [0,1,0], 'LineStyle', '--', 'LineWidth',2.5);
text(0.55, 0.8, ['$\tau= ',num2str(round(F1_c.tau, 2)),'$'], ...
    'units', 'normalized', 'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor','none');
text(0.55, 0.7, ['$p= ',num2str(round(F1_c.p_mle, 2)),'$'], ...
    'units', 'normalized', 'Interpreter','latex',...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor', 'none');
legend([F1,F2,F3],{'real data','surrogate data','fit'},'Location','southwest',...
    'FontName','Arial','FontSize',15,'EdgeColor',[1,1,1])
legend('boxoff')
xlabel('avalanche duration T', 'FontName', 'Arial');
ylabel('P(T)', 'FontName', 'Arial');
set(gca, 'FontName', 'Arial', 'FontSize',18, ...
    'XTick',[1,10,100,1000], 'YTick',[0.00001,0.0001,0.001,0.01,0.1,1]);
title('C', 'FontName', 'Arial', 'FontSize', 24, ...
    'units', 'normalized', 'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom');
grid off; AX1.LineWidth = 2; box(AX1,'off'); hold off
%% figure 1 d
AX1 = subplot(2,3,5);
Gamma_mle = (Tau_mle-1) / (Alpha_mle-1);
[Lifetime,Average_size] = ...
    lifetimeAverageSize(AvaD_AllSubject,AvaS_AllSubject);
[Gamma_nlsfit_1] = createFit_pl_nonlinearLS(Lifetime(Tmin2fit:Tmax2fit),...
    Average_size(Tmin2fit:Tmax2fit));
F1_d.lifetime = Lifetime;
F1_d.averageSize = Average_size;
F1_d.lifetimeFitRange = Tmin2fit:Tmax2fit;
F1_d.averageSizeFit = (Gamma_nlsfit_1.a).*(Tmin2fit:Tmax2fit).^(Gamma_nlsfit_1.b);
F1_d.gammaFromFit = Gamma_nlsfit_1.b;
F1_d.gammaFromTauAlpha = Gamma_mle;
F1 = loglog(F1_d.lifetime, F1_d.averageSize, 'Color', [0.5,0.5,0.5], ...
    'LineStyle', 'none', 'LineWidth', 2, ...
    'Marker', 'o', 'MarkerSize',6);
hold on
load('HY_96_surrogate\noFC\noFC_avalanche_analysis.mat', ...
    'Avalanche_surrogate_nofc')
F2 = loglog(Avalanche_surrogate_nofc.Lifetime,...
    Avalanche_surrogate_nofc.AverageSize,...
    'Color', [0.7,0.7,0.7], 'LineStyle', 'none', 'LineWidth', 1, ...
    'Marker', '<', 'MarkerSize',6);
clear Avalanche_surrogate_nofc
F3 = loglog(F1_d.lifetimeFitRange, F1_d.averageSizeFit, 'Color', [0,1,0], ...
    'LineStyle', '--', 'LineWidth',2.5);
text(0.3, 0.8, ...
    ['$\frac{1-\tau}{1-\alpha}= ', num2str(round(F1_d.gammaFromTauAlpha,2)), '$'], ...
    'units', 'normalized', 'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor', 'none');
text(0.3, 0.7, ...
    ['$\gamma = ',num2str(round(F1_d.gammaFromFit,2)), '$'], ...
    'units', 'normalized', 'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor', 'none');
legend([F1,F2,F3],{'real data','surrogate data','fit'},'Location','southeast',...
    'FontName','Arial','FontSize',15,'EdgeColor',[1,1,1])
legend('boxoff')
xlabel('duration T', 'FontName', 'Arial');
ylabel('average size', 'FontName', 'Arial');
set(gca, 'FontName', 'Arial', 'FontSize', 18);
title('D', 'FontName', 'Arial', 'FontSize', 24, ...
    'units', 'normalized', 'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom');
box(AX1, 'off'); AX1.LineWidth = 2; grid off; hold off
%% figure 1 e
AX1 = subplot(2,3,6);
load('HY_96\alpha_bp_gamma_diffthd.mat', 'alpha_mle')
load('HY_96\alpha_bp_gamma_diffthd.mat', 'bpGroup')
F1_e.branching = bpGroup(1:2:9);
F1_e.alpha = alpha_mle(1:2:9);
F1_e.threshold = 1.0:0.2:1.8;

plot(F1_e.branching, F1_e.alpha, 'Color', [0,0,0], ...
    'LineStyle', '--', 'LineWidth', 2, ...
    'Marker', 'o', 'MarkerSize', 6);
hold on
plot([0.6,1.2], [1.5,1.5], 'Color', [0,0,1], ...
    'LineStyle', '--', 'LineWidth', 2, ...
    'Marker', 'none', 'MarkerSize', 6);
plot([1,1], [1.3,1.9], 'Color', [0,0,1], ...
    'LineStyle', '--', 'LineWidth', 2, ...
    'Marker', 'none', 'MarkerSize',6);
axis([0.6,1.2,1.3,1.9]);
text(bpGroup(1)+0.01, alpha_mle(1)+0.03, ...
    '$1.0\ SD$', 'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor','none');
text(bpGroup(5)+0.01, alpha_mle(5)+0.03, ...
    '$1.4\ SD$', 'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor','none');
text(bpGroup(9)+0.01, alpha_mle(9)+0.03, ...
    '$1.8\ SD$', 'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], 'FontName', 'Arial', ...
    'FontSize', 20, 'EdgeColor', 'none');
xlabel('branching \sigma', 'FontName', 'Arial');
ylabel('\alpha', 'FontName', 'Arial');
set(gca, 'FontName', 'Arial', 'FontSize', 18);
title('E', 'FontName', 'Arial', 'FontSize', 24, ...
    'units', 'normalized', 'position', [-1/18,1+1/18], ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom');
box(AX1,'off'); AX1.LineWidth=2; grid off; hold off
%% save
save('Figure_1.mat', 'F1_a', 'F1_d', 'F1_c', 'F1_d', 'F1_e');