%% power branching parameter
clc; clear; close all
figure(...
      'Color', 'w', ...
      'Units', 'Normalized', ...
      'Name',  'branching parameter analysis', ...
      'Position', [0.1 0.3 0.5 0.5]);
AX1 = subplot(1,2,1);
load(['D:\criticality_cognitive\project_synchrony_avalanche_fluid_Iq\',...
    'b_MS_SE_STATIC\MS_SE_BA246_RS.mat'], 'syn')
load('BN_246\Avalanches_define.mat', 'BP')
Branching = BP(:,1);
MS = syn(:,1);
[syn_branching] = createFit_poly1(MS, Branching);
[r_syn_bran, p_syn_bran] = corr(MS, Branching);
b = syn_branching.p1; 
c = syn_branching.p2; 
MSfit = min(syn(:,1)) : 0.01 : max(syn(:,1)) + 0.01;
BranchingFit = b .* MSfit + c;
lineFitR = r_syn_bran;
lineFitP = p_syn_bran;
f1 = plot([min(MS),max(MS)], [1,1], ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5); 
hold on
plot(MS, Branching, ...
    'Color', [0.50,0.50,0.50], ...
    'color', [0.5,0.5,0.5], ...
    'Marker', 'o', ...
    'MarkerSize', 6, ...
    'LineStyle', 'none', ...
    'LineWidth', 2);
f2=plot(MSfit, BranchingFit, ...
    'Color', [1, 0, 0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
set(gca, 'FontName', 'Arial', 'FontSize', 12);
legend([f1, f2], ...
    '$\sigma=1$', '$fit$', ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'EdgeColor', [1,1,1]);
legend('boxoff');
xlabel('Atlas_2_4_6 MS <r>', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
ylabel('branching \sigma', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
text(0.15, 0.7, ...
    ['$R=', num2str(round(lineFitR,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
text(0.15, 0.6, ...
    ['$p=', num2str(round(lineFitP,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
title('a', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units', 'normalized', ...
    'position', [-1/18,1+1/50], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
box(AX1,'off');
AX1.LineWidth = 2; 
grid off;
hold off

clear
AX1 = subplot(1,2,2);
load(['D:\criticality_cognitive\project_synchrony_avalanche_fluid_Iq\',...
    'b_MS_SE_STATIC\MS_SE_Z1024_RS.mat'], 'syn')
load('Z_1024\Avalanches_define.mat', 'BP')
Branching = BP(:,1);
syn(6) = [];
Branching(6) = [];
[syn_branching] = createFit_poly1(syn(:,1), Branching);
[r_syn_bran, p_syn_bran] = corr(syn(:,1), Branching);
b = syn_branching.p1; 
c = syn_branching.p2; 
MS = syn(:,1);
MSfit = min(syn(:,1)) : 0.01 : max(syn(:,1)) + 0.01;
BranchingFit = b .* MSfit + c;
lineFitR = r_syn_bran;
lineFitP = p_syn_bran;
f1 = plot([min(MS),max(MS)], [1,1], ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5); 
hold on
plot(MS, Branching, ...
    'Color', [0.50,0.50,0.50], ...
    'color', [0.5,0.5,0.5], ...
    'Marker', 'o', ...
    'MarkerSize', 6, ...
    'LineStyle', 'none', ...
    'LineWidth', 2);
f2=plot(MSfit, BranchingFit, ...
    'Color', [1, 0, 0], ...
    'LineStyle', '--', ...
    'LineWidth', 2.5);
set(gca, 'FontName', 'Arial', 'FontSize', 12);
legend([f1, f2], ...
    '$\sigma=1$', '$fit$', ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'EdgeColor', [1,1,1]);
legend('boxoff');
xlabel('Atlas_1_0_2_4 MS <r>', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
ylabel('branching \sigma', ...
    'FontName', 'Arial', ...
    'FontSize', 15);
text(0.15, 0.7, ...
    ['$R=', num2str(round(lineFitR,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
text(0.15, 0.6, ...
    ['$p=', num2str(round(lineFitP,2)), '$'], ...
    'units', 'normalized', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
title('b', ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'units', 'normalized', ...
    'position', [-1/18,1+1/50], ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom');
box(AX1,'off');
AX1.LineWidth = 2; 
grid off;
hold off