%% supplement figure about the power law for BN246 and z1024
clc; clear; close all
addpath('D:\supplyment_dataANDcode\z_function\CritAnalysisSoftwarePackage2016-04-25')
 figure(...
      'Color', 'w', ...
      'Units', 'Normalized', ...
      'Name',  'Power law analysis', ...
      'Position', [0.1 0.3 0.8 0.5]);
%%
load('BN_246\Avalanches_1.7.mat')
AvaDuration =  AvaD_AllSubject;
AvaSize = AvaS_AllSubject;
SizeFitRange = [7,40];
DurationFitRange = [3,10];
% average size across avalanche with same lifetime
[Lifetime, AverageSize]=lifetimeAverageSize(AvaDuration, AvaSize);
% calculate the distribution of avalanche size and duration
    SizeRange = min(AvaSize) : 1 : max(AvaSize);
    AvaSizeHist = hist(AvaSize, SizeRange);
    AvaSizeHist = AvaSizeHist/AvaSizeHist(1);
    
    DurationRange = min(AvaDuration) : 1 : max(AvaDuration);
    AvaDurationHist = hist(AvaDuration,DurationRange);
    AvaDurationHist = AvaDurationHist/AvaDurationHist(1);
% power law fit
    [Alpha, Smin2fit, Smax2fit] = plmle(AvaSize, 'xmin', SizeFitRange(1), 'xmax', SizeFitRange(2));
    [P_alpha] = pvcalc(AvaSize, Alpha, 'xmin',Smin2fit,'xmax',Smax2fit);
    SizePLFitRange = Smin2fit:Smax2fit;
    SizePLFitDistribution = (Smin2fit:Smax2fit).^(-Alpha);

    [Tau, Tmin2fit, Tmax2fit] = plmle(AvaDuration,'xmin', DurationFitRange(1), 'xmax', DurationFitRange(2));
    [P_tau] = pvcalc(AvaDuration, Tau, 'xmin',Tmin2fit,'xmax',Tmax2fit);
    DurationPLFitRange = Tmin2fit:Tmax2fit;
    DurationPLFitDistribution = (Tmin2fit:Tmax2fit).^(-Tau);
        
    [Gamma_nlsfit] = createFit_pl_nonlinearLS(Lifetime(Tmin2fit:Tmax2fit), AverageSize(Tmin2fit:Tmax2fit));
    Gamma_fit = Gamma_nlsfit.b;
    Gamma_alpga_tau = (Tau-1) / (Alpha-1);
    LifetimeFitRange = Tmin2fit:Tmax2fit;
    AverageSizeFit = (Gamma_nlsfit.a).*(Tmin2fit:Tmax2fit).^(Gamma_fit);
% plot the distribution of avalanche size and duration
  AX1 = subplot(3,3,1);
    loglog(SizeRange, AvaSizeHist, ...
    'Color', [0.50, 0.50, 0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize',6);
    hold on;
    loglog(SizePLFitRange, SizePLFitDistribution, ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth',2.5);
    text(0.7, 0.9, ...
         ['$\alpha= ', num2str(round(Alpha, 2)), '$'], ...
         'units', 'normalized', ...
         'Interpreter','latex', ...
         'Color', [0.00,0.00,0.00], ...
         'FontName', 'Arial', ...
         'FontSize', 20, ...
         'EdgeColor','none');
    text(0.7, 0.7, ...
         ['$p= ', num2str(round(P_alpha, 2)), '$'], ...
         'units', 'normalized', ...
         'Interpreter','latex',...
         'Color', [0.00,0.00,0.00], ...
         'FontName', 'Arial', ...
         'FontSize', 20, ...
         'EdgeColor','none');
     xlabel('avalanche size S', ...
            'FontName', 'Arial');
     ylabel('P(S)', ...
            'FontName', 'Arial');
     set(gca, ...
         'FontName', 'Arial', ...
         'FontSize',18, ...
         'XTick', [1,10,100,1000], ...
         'YTick', [0.00001,0.0001,0.001,0.01,0.1,1]);
     grid off; 
     AX1.LineWidth = 2; 
     box(AX1,'off'); 
     hold off
     title('a', ...
           'FontName','Arial', ...
           'FontSize', 24, ...
           'FontWeight', 'bold', ....
           'units', 'normalized', ...
           'position', [-1/6,1-1/30], ...
           'HorizontalAlignment', 'right', ...
           'VerticalAlignment','bottom');
%%
      AX1 = subplot(3,3,2);
      loglog(DurationRange, AvaDurationHist, ...
             'Color', [0.50,0.50,0.50], ...
             'LineStyle', 'none', ...
             'LineWidth', 2, ...
             'Marker', 'o', ...
             'MarkerSize',6);
      hold on;
      loglog(DurationPLFitRange, DurationPLFitDistribution, ...
             'Color', [0,1,0], ...
             'LineStyle', '--', ...
             'LineWidth',2.5);
      text(0.7, 0.9, ...
           ['$\tau= ',num2str(round(Tau, 2)),'$'], ...
            'units', 'normalized', ...
            'Interpreter','latex', ...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor','none');
      text(0.7, 0.7, ...
           ['$p= ',num2str(round(P_tau, 2)),'$'], ...
            'units', 'normalized', ...
            'Interpreter','latex',...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor', 'none');
      xlabel('avalanche duration T', ...
             'FontName', 'Arial');
      ylabel('P(T)', ...
             'FontName', 'Arial');
      set(gca, ...
          'FontName', 'Arial', ...
          'FontSize',18, ...
          'XTick',[1,10,100,1000], ...
          'YTick',[0.00001,0.0001,0.001,0.01,0.1,1]);
      title('Atlas_2_4_6', ...
            'FontName','Arial', ...
            'FontSize', 20, ...
            'FontWeight', 'bold');
      grid off; 
      AX1.LineWidth = 2; 
      box(AX1,'off'); 
      hold off
%%
      AX1 = subplot(3,3,3);
      loglog(Lifetime, AverageSize, ...
             'Color', [0.5,0.5,0.5], ...
             'LineStyle', 'none', ...
             'LineWidth', 2, ...
             'Marker', 'o', ...
             'MarkerSize',6);
      hold on
      loglog(LifetimeFitRange, AverageSizeFit, ...
             'Color', [0,1,0], ...
             'LineStyle', '--', ...
             'LineWidth',2.5);
      text(0.2, 0.9, ...
           ['$\frac{1-\tau}{1-\alpha}= ', num2str(round(Gamma_alpga_tau,2)), '$'], ...
           'units', 'normalized', ...
           'Interpreter', 'latex', ...
           'Color', [0.00,0.00,0.00], ...
           'FontName', 'Arial', ...
           'FontSize', 20, ...
           'EdgeColor', 'none');
      text(0.2, 0.7, ...
           ['$\gamma = ',num2str(round(Gamma_fit,2)), '$'], ...
            'units', 'normalized', ...
            'Interpreter', 'latex', ...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor', 'none');
      xlabel('duration T', ...
             'FontName', 'Arial');
      ylabel('average size', ...
             'FontName', 'Arial');
      set(gca, ...
             'FontName', 'Arial', ...
             'FontSize', 18);
      
      box(AX1, 'off'); 
      AX1.LineWidth = 2; 
      grid off; 
      hold off
%%
% Z1024
clear
load('Z_1024\Avalanches_2.mat')
AvaDuration =  AvaD_AllSubject;
AvaSize = AvaS_AllSubject;
SizeFitRange = [4,60];
DurationFitRange = [4,10];
% average size across avalanche with same lifetime
[Lifetime, AverageSize]=lifetimeAverageSize(AvaDuration, AvaSize);
% calculate the distribution of avalanche size and duration
    SizeRange = min(AvaSize) : 1 : max(AvaSize);
    AvaSizeHist = hist(AvaSize, SizeRange);
    AvaSizeHist = AvaSizeHist/AvaSizeHist(1);
    
    DurationRange = min(AvaDuration) : 1 : max(AvaDuration);
    AvaDurationHist = hist(AvaDuration,DurationRange);
    AvaDurationHist = AvaDurationHist/AvaDurationHist(1);
% power law fit
    [Alpha, Smin2fit, Smax2fit] = plmle(AvaSize, 'xmin', SizeFitRange(1), 'xmax', SizeFitRange(2));
    [P_alpha] = pvcalc(AvaSize, Alpha, 'xmin',Smin2fit,'xmax',Smax2fit);
    SizePLFitRange = Smin2fit:Smax2fit;
    SizePLFitDistribution = (Smin2fit:Smax2fit).^(-Alpha);

    [Tau, Tmin2fit, Tmax2fit] = plmle(AvaDuration,'xmin', DurationFitRange(1), 'xmax', DurationFitRange(2));
    [P_tau] = pvcalc(AvaDuration, Tau, 'xmin',Tmin2fit,'xmax',Tmax2fit);
    DurationPLFitRange = Tmin2fit:Tmax2fit;
    DurationPLFitDistribution = (Tmin2fit:Tmax2fit).^(-Tau);
        
    [Gamma_nlsfit] = createFit_pl_nonlinearLS(Lifetime(Tmin2fit:Tmax2fit), AverageSize(Tmin2fit:Tmax2fit));
    Gamma_fit = Gamma_nlsfit.b;
    Gamma_alpga_tau = (Tau-1) / (Alpha-1);
    LifetimeFitRange = Tmin2fit:Tmax2fit;
    AverageSizeFit = (Gamma_nlsfit.a).*(Tmin2fit:Tmax2fit).^(Gamma_fit);
% plot the distribution of avalanche size and duration
  AX1 = subplot(3,3,4);
    loglog(SizeRange, AvaSizeHist, ...
    'Color', [0.50, 0.50, 0.50], ...
    'LineStyle', 'none', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize',6);
    hold on;
    loglog(SizePLFitRange, SizePLFitDistribution, ...
    'Color', [0,1,0], ...
    'LineStyle', '--', ...
    'LineWidth',2.5);
    text(0.7, 0.9, ...
         ['$\alpha= ', num2str(round(Alpha, 2)), '$'], ...
         'units', 'normalized', ...
         'Interpreter','latex', ...
         'Color', [0.00,0.00,0.00], ...
         'FontName', 'Arial', ...
         'FontSize', 20, ...
         'EdgeColor','none');
    text(0.7, 0.7, ...
         ['$p= ', num2str(round(P_alpha, 2)), '$'], ...
         'units', 'normalized', ...
         'Interpreter','latex',...
         'Color', [0.00,0.00,0.00], ...
         'FontName', 'Arial', ...
         'FontSize', 20, ...
         'EdgeColor','none');
     xlabel('avalanche size S', ...
            'FontName', 'Arial');
     ylabel('P(S)', ...
            'FontName', 'Arial');
     set(gca, ...
         'FontName', 'Arial', ...
         'FontSize',18, ...
         'XTick', [1,10,100,1000], ...
         'YTick', [0.00001,0.0001,0.001,0.01,0.1,1]);
     grid off; 
     AX1.LineWidth = 2; 
     box(AX1,'off'); 
     hold off
     title('b', ...
           'FontName','Arial', ...
           'FontSize', 24, ...
           'FontWeight', 'bold', ....
           'units', 'normalized', ...
           'position', [-1/6,1-1/30], ...
           'HorizontalAlignment', 'right', ...
           'VerticalAlignment','bottom');
%%
      AX1 = subplot(3,3,5);
      loglog(DurationRange, AvaDurationHist, ...
             'Color', [0.50,0.50,0.50], ...
             'LineStyle', 'none', ...
             'LineWidth', 2, ...
             'Marker', 'o', ...
             'MarkerSize',6);
      hold on;
      loglog(DurationPLFitRange, DurationPLFitDistribution, ...
             'Color', [0,1,0], ...
             'LineStyle', '--', ...
             'LineWidth',2.5);
      text(0.7, 0.9, ...
           ['$\tau= ',num2str(round(Tau, 2)),'$'], ...
            'units', 'normalized', ...
            'Interpreter','latex', ...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor','none');
      text(0.7, 0.7, ...
           ['$p= ',num2str(round(P_tau, 2)),'$'], ...
            'units', 'normalized', ...
            'Interpreter','latex',...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor', 'none');
      xlabel('avalanche duration T', ...
             'FontName', 'Arial');
      ylabel('P(T)', ...
             'FontName', 'Arial');
      set(gca, ...
          'FontName', 'Arial', ...
          'FontSize',18, ...
          'XTick',[1,10,100,1000], ...
          'YTick',[0.00001,0.0001,0.001,0.01,0.1,1]);
      title('Atlas_1_0_2_4', ...
            'FontName','Arial', ...
            'FontSize', 20, ...
            'FontWeight', 'bold');
      grid off; 
      AX1.LineWidth = 2; 
      box(AX1,'off'); 
      hold off
%%
      AX1 = subplot(3,3,6);
      loglog(Lifetime, AverageSize, ...
             'Color', [0.5,0.5,0.5], ...
             'LineStyle', 'none', ...
             'LineWidth', 2, ...
             'Marker', 'o', ...
             'MarkerSize',6);
      hold on
      loglog(LifetimeFitRange, AverageSizeFit, ...
             'Color', [0,1,0], ...
             'LineStyle', '--', ...
             'LineWidth',2.5);
      text(0.2, 0.9, ...
           ['$\frac{1-\tau}{1-\alpha}= ', num2str(round(Gamma_alpga_tau,2)), '$'], ...
           'units', 'normalized', ...
           'Interpreter', 'latex', ...
           'Color', [0.00,0.00,0.00], ...
           'FontName', 'Arial', ...
           'FontSize', 20, ...
           'EdgeColor', 'none');
      text(0.2, 0.7, ...
           ['$\gamma = ',num2str(round(Gamma_fit,2)), '$'], ...
            'units', 'normalized', ...
            'Interpreter', 'latex', ...
            'Color', [0.00,0.00,0.00], ...
            'FontName', 'Arial', ...
            'FontSize', 20, ...
            'EdgeColor', 'none');
      xlabel('duration T', ...
             'FontName', 'Arial');
      ylabel('average size', ...
             'FontName', 'Arial');
      set(gca, ...
             'FontName', 'Arial', ...
             'FontSize', 18);
      box(AX1, 'off'); 
      AX1.LineWidth = 2; 
      grid off; 
      hold off
%%
clear
%bn246
load('ava_fit_different_thr\BN246.mat')
for S = 1:19
    bpGroup(S) = BP_GROUP(S).EventBigThan0;
    alpha_mle(S) = Criterion(S).Alpha;
end
AX1 = subplot(3,2,5);
plot(bpGroup(4:2:12),alpha_mle(4:2:12), ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on
plot([0.6,1.2], [1.5,1.5], ...
    'Color', [0,0,1], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'none', ...
    'MarkerSize', 6);
plot([1,1], [1.3,1.9], ...
    'Color', [0,0,1], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'none', ...
    'MarkerSize',6);
text(bpGroup(4)+0.01, alpha_mle(4)+0.03, ...
    '$1.3\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(6)+0.01, alpha_mle(6)+0.03, ...
    '$1.5\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(8)+0.01, alpha_mle(8)+0.03, ...
    '$1.7\ SD$', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(10)+0.01, alpha_mle(10)+0.03, ...
    '$1.9\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
text(bpGroup(12)+0.01, alpha_mle(12)+0.03, ...
    '$2.1\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
xlabel('Atlas_2_4_6 branching \sigma', ...
    'FontName', 'Arial');
ylabel('Atlas_2_4_6 \alpha', ...
    'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 18);
title('c', ...
      'FontName','Arial', ...
      'FontSize', 24, ...
      'FontWeight', 'bold', ....
      'units', 'normalized', ...
      'position', [-1/11,1-1/30], ...
      'HorizontalAlignment', 'right', ...
      'VerticalAlignment','bottom');

box(AX1,'off'); 
AX1.LineWidth=2; 
grid off; 
hold off
%%
clear
%Z1024 
load('ava_fit_different_thr\Z1024.mat')
for S = 1:20
    bpGroup(S) = BP_GROUP(S).EventBigThan0;
    alpha_mle(S) = Criterion(S).Alpha;
end
AX1 = subplot(3,2,6);
plot(bpGroup(7:2:15),alpha_mle(7:2:15), ...
    'Color', [0.5,0.5,0.5], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 6);
hold on
plot([0.6,1.2], [1.5,1.5], ...
    'Color', [0,0,1], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'none', ...
    'MarkerSize', 6);
plot([1,1], [1.3,1.8], ...
    'Color', [0,0,1], ...
    'LineStyle', '--', ...
    'LineWidth', 2, ...
    'Marker', 'none', ...
    'MarkerSize',6);
text(bpGroup(7)+0.01, alpha_mle(7)+0.03, ...
    '$1.6\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(9)+0.01, alpha_mle(9)+0.03, ...
    '$1.8\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(11)+0.01, alpha_mle(11)+0.03, ...
    '$2.0\ SD$', ...
    'Interpreter', 'latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor','none');
text(bpGroup(13)+0.01, alpha_mle(13)+0.03, ...
    '$2.2\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
text(bpGroup(15)+0.01, alpha_mle(15)+0.03, ...
    '$2.4\ SD$', ...
    'Interpreter','latex', ...
    'Color', [0.00,0.00,0.00], ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'EdgeColor', 'none');
xlabel('Atlas_1_0_2_4 branching \sigma', ...
    'FontName', 'Arial');
ylabel('Atlas_1_0_2_4 \alpha', ...
    'FontName', 'Arial');
set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 18);
title('d', ...
      'FontName','Arial', ...
      'FontSize', 24, ...
      'FontWeight', 'bold', ....
      'units', 'normalized', ...
      'position', [-1/11,1-1/30], ...
      'HorizontalAlignment', 'right', ...
      'VerticalAlignment','bottom');
box(AX1,'off'); 
AX1.LineWidth=2; 
grid off; 
hold off
